Add 'continue' statement to mysqltest
MariaDB/server pull request #1585
Opened 2020-06-09 09:20 UTC by DwarfMason

I've added continue statement to mysqltest.cc to improve flexibility of test framework.

2021-02-16 08:57 UTC, FooBarrior requested changes

2021-02-16 08:57 UTC, FooBarrior commented on client/mysqltest.cc
> +void do_continue(struct st_command* command){
Can you please move the brace to the next line?

2022-09-18 17:37 UTC, LinuxJedi commented
Hi @DwarfMason,

I'm attempting to assist in getting older pull requests moving along again. If you could please rebase this against the latest development branch (currently 10.11), I can make sure it gets reviewed appropriately.

Many thanks!

2022-09-18 20:51 UTC, vuvova commented
@LinuxJedi, haphazard adding of features to mysqltest is what got it where it is now. We need some plan and understanding where we want it to be before extending it any more. See https://jira.mariadb.org/browse/MDEV-12130

2022-09-19 07:44 UTC, LinuxJedi commented
> @LinuxJedi, haphazard adding of features to mysqltest is what got it where it is now. We need some plan and understanding where we want it to be before extending it any more. See https://jira.mariadb.org/browse/MDEV-12130

Sorry @vuvova, my bad. I connected the dots of history incorrectly here.

OK, so, @DwarfMason if you do want to continue with this work, there should probably be a larger discussion around it. I recommend contacting the mailing list referencing the MDEV to discuss it.

2023-09-15 18:14 UTC, FooBarrior commented
@LinuxJedi if we're merging #1580, then, I suppose, this one, being symmetric, should go as well

2025-02-17 11:25 UTC, vuvova commented
`mysqltest` language is too complex and redundant from one side and very ridiculously limited from the other. Adding minor optional nice-to-have features is not a priority now, as it doesn't help to solve either of its main problems.

2025-02-17 11:25 UTC, closed without merging