MDEV-23468: inline_mysql_socket_send: Assertion `mysql_socket.fd != -…
MariaDB/server pull request #1709
Opened 2020-12-02 13:11 UTC by mkaruza

…1' failed on shutdown

VIO should be shutdownwith `vio_shutdown` instead of `vio_close` in `thd->disconnect()`.

2020-12-02 13:11 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=1709) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=1709) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=1709) it.</sub>

2020-12-03 12:26 UTC, montywi reviewed
I am not sure that this is the best possible solution.
wsrep_close_thread does similar work asthd->set_killed(KILL_CONNECTION);

2020-12-03 12:35 UTC, montywi requested changes
I am not sure that this is a working solution
The wsrep_close_thread() call does similar work as
thd->set_killed() and thd->awake() which was already done by kill_all_threads
In addition the thd->awake() is by default already closing the socket with shutdown
(look in THD::awake_no_mutex() when compiled with SIGNAL_WITH_VIO_CLOSE, which is set by default).
In theory, kill_remaining_threads could do like in awake:
 if (thd->active_vio)
   vio_shutdown(active_vio, SHUT_RDWR);

In general, it would be good if the kill methods used in wsrep_mysqld.cc would reuse the methods used in mysqld.cc when taking down the server.  That way we would have only one method to kill threads and less potential problems.

Can you please check if this helps with the problem?

2020-12-22 09:34 UTC, janlindstrom commented
Merged to 10.4 in b79b3ff65571287882724b7b5cbe21004594a4d9. Actual refactoring of should be done in 10.6 at the earliest.

2020-12-22 09:34 UTC, closed without merging