Improve sys.table_exists()
MariaDB/server pull request #1814
Opened 2021-04-26 23:16 UTC by federico-razzoli

Improve `table_exists()` in several ways:

- Don't try to CREATE+DROP temporary tables in information_schema or performance_schema.
- New possible output values: 'SYSTEM VIEW', 'SEQUENCE'. Previously it failed with error in these cases.
- If the table type is 'SYSTEM VERSIONED', return 'BASE TABLE'. Previously it failed.

2021-04-26 23:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=1814) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=1814) before we can accept your contribution.<br/><hr/>**Federico Razzoli** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=1814) it.</sub>

2021-04-27 00:22 UTC, federico-razzoli commented
Re Zulip: Previously `table_exists('information_schema', 'any table', @r)` would fail with an error, because table_exists would attempt to create a temp table in the i_s, which is not possible. This PR solves the problem by not attempting to create a temp table in i_s or p_s.

2021-04-27 06:23 UTC, vaintroub commented
@federico-razzoli , looks good in general, but a test case  is missing . A test case should be such that it fails without your patch , and succeeds with your patch.  The changes should have some test coverage, i.e  views, system version, and sequence tables should be there, as well as I_S and P_S tables.
 
you can extend mysql-test/suite/sysschema/t/pr_table_exists.test for this .
you'd need to run  mysql-test-run.pl pr_table_exists --record to record corresponding changes in the pr_table_exists.result

2021-05-05 18:57 UTC, vaintroub requested changes
@federico-razzoli , looks good in general, but a test case is missing . A test case should be such that it fails without your patch , and succeeds with your patch. The changes should have some test coverage, i.e views, system version, and sequence tables should be there, as well as I_S and P_S tables.

you can extend mysql-test/suite/sysschema/t/pr_table_exists.test for this .
you'd need to run

mysql-test-run.pl pr_table_exists --record

to record corresponding changes in the pr_table_exists.result

2021-11-30 12:39 UTC, robertbindar commented
Hey @federico-razzoli! I know it's been a long time since you submitted this and context switching again might kill lots of your time. Can you please let me know if you're still willing to work on this and add the test case Wlad suggested?

2022-04-27 10:44 UTC, vaintroub approved these changes

2022-04-27 11:06 UTC, vaintroub commented
Rebased, added tests and pushed as MDEV-28340

2022-04-28 20:18 UTC, federico-razzoli commented
Thank you for taking care of this contribution that I left unfinished.

2022-04-29 06:53 UTC, grooverdan commented
closed via 3fe656e629f00c1fc823f49d1072e3aa1ccda12e

2022-04-29 06:53 UTC, closed without merging