Deb: Misc cleanup and autobake-deb.sh and Salsa-CI fixes
MariaDB/server pull request #1835
Opened 2021-05-24 04:26 UTC by ottok

* Clean up autobake-deb.sh

  - No need to define any TokuDB rules, there is no such package
  - No need to define RocksDB arch, it already has "Architecture:" line
  - No need to dh-systemd backwards compat stanza, neither Debian Jessie
    nor Ubuntu Xenial has any new MariaDB 10.5 releases anymore
  - Minor spelling fixes

* Ensure dch runs non-interactively so builds pass with new dch version

  A recent version of dch (available in Ubuntu Hirsute and Debian Bullseye)
  had a change in behaviour that it started prompting if the DEBEMAIL or
  EMAIL variable as unset, asking for confirmation. We can't have anything
  interactive in our build scripts, so prevent this prompt by giving
  --controlmaint to the command, so it always uses the name and email from
  the debian/control file and does not prompt anything.

  The command-line argument has been around for a long time, so it is safe
  to use on all Debian/Ubuntu builds we have.

  See https://manpages.debian.org/jessie/devscripts/dch.1.en.html

  Since MariaDB 10.5 is the oldest release we still release for Ubuntu Hisute
  and Debian Bullseye, merge this on 10.5 and from there merge up to latest.
  No need to consider 10.2, 10.3 and 10.4 as those will not be released for
  Ubuntu Bullseye or Ubuntu Hirsute.

* Minor Salsa-CI cleanup

  - Fix spelling (synced from downstream Debian)
  - Extend with libmariadb-dev using test to verify client library
    continues to work and actually can be used to compile a program

* Many minor spelling fixes (synced from downstream Debian)

2021-05-29 09:02 UTC, vuvova requested changes
There's clearly some misunderstanding here.
1. why "*.jar files are not being built"?
2. if "*.jar files are not being built" then how can they be "already included in the
mariadb-test-data package"?
3. if they are, indeed, "already included in the mariadb-test-data package" — then it's not enough, there files are *not* test data, but part of the CONNECT feature that users are expected to use, they're *not* only for testing.

2021-05-30 03:31 UTC, ottok commented
Thanks @vuvova for taking a look. The first commit fixes the dh-systemd issue and does general cleanup, result:
https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/258164
![image](https://user-images.githubusercontent.com/668724/120090855-76b1d180-c10e-11eb-8c92-069d61a6139c.png)

Failures are due to commit d7321893 that tries to install files that don't exist (as layouted in CMake) at that location. Thus reverting it makes the builds fully pass, as shown in https://salsa.debian.org/mariadb-team/mariadb-server/-/pipelines/258201

![image](https://user-images.githubusercontent.com/668724/120090884-acef5100-c10e-11eb-88a9-313f3b54a8be.png)

Looking at build logs on [10.5 on old buildbot](http://buildbot.askmonty.org/buildbot/builders/kvm-deb-sid-amd64/builds/12186/steps/compile/logs/stdio) is shows:
```
-rw-r--r-- root/root ./usr/share/mysql/JavaWrappers.jar  
-rw-r--r-- root/root ./usr/share/mysql/JdbcInterface.jar
...
-rw-r--r-- root/root ./usr/share/mysql/mysql-test/plugin/connect/connect/std_data/JavaWrappers.jar  
-rw-r--r-- root/root ./usr/share/mysql/mysql-test/plugin/connect/connect/std_data/JdbcMariaDB.jar
```
http://buildbot.askmonty.org/buildbot/builders/kvm-deb-sid-amd64/builds/12186/steps/compile/logs/stdio

I wonder what magic buildbot is doing. Maybe there is some extra Java package that causes different behavior. All build dependencies should be documented and explicit. Clearly now in clean environments on CI or on my local laptop the build fails.

2021-05-30 03:51 UTC, ottok commented
Indeed, comparing the configure stages of buildbot build and a clean build, clearly buildbot environment has extra Java thing installed:
![image](https://user-images.githubusercontent.com/668724/120091378-4a4c8400-c113-11eb-812d-f25f3ddc505b.png)

Feel free to make your suggested change on the 10.6 branch.

From 10.5 it must however be reverted. We cannot introduce new build dependencies or significant new files in a stable release 10.5.

2021-05-30 04:04 UTC, ottok commented
Related, I created https://jira.mariadb.org/browse/MDEV-25819 to clean up extra dependencies.

@vuvova As I have expressed a couple of time, I'd rather review the changes to debian/* files or make the changes myself on your requests, than having to run into regressions while working on something else and then having to rush to debugging and cleanup work, that could have been avoided from the start. If you have Debian packaging changes, feel free to make a PR out of them an assign to me.

_(And related, I really hope MariaDB would have protected branches so nobody can push stuff that breaks something CI easily can detect, and that PRs in general would be more often used to keep the quality up of changes.)_

2021-05-31 10:26 UTC, vuvova commented
I see. Indeed, jar files weren't built before, and Java isn't in build-depends.

Okay, I understand, that you won't want to add new build-depends in 10.2. In this case, please, revert my changes to  debian/mariadb-plugin-connect.install (but not the rest of that commit)

2021-06-01 14:55 UTC, ottok commented
@vuvova Revert commit updated as requested

2021-06-04 06:04 UTC, ottok commented
Does @grooverdan want to chip in here before this is merged? The build is currently broken on a stable release (10.5) so I feel merging this is kind of urgent...

2021-06-04 08:07 UTC, grooverdan commented
Looks fine and appears to address review comments.

2021-06-06 03:54 UTC, merged

2021-06-06 07:19 UTC, ottok commented
Split the second commit on a new PR as it needs to go to 10.2 (and be merged up to 10.5): https://github.com/MariaDB/server/pull/1851