MDEV-26015: Set DH param automatically
MariaDB/server pull request #1869
Opened 2021-06-30 20:35 UTC by 9EOR9

So far  MariaDB Server creates a DH (Diffie Hellman) parameter with a
fixed length (= 2048). This leads to the limitation that, for example, the
use of a DHE cipher suite requires a server certificate with an RSA key
of the same length.

To remedy this, the DH parameter is now automatically set by OpenSSL or WolfSSL
during the TLS handshake (taking into account the key length used
of the server certificate).

While WoldSSL supports this by default, OpenSSL has to activate this using the
SSL_CTX_set_dh_auto macro. OpenSSL versions < 1.0.2  doesn't support this feature
and use the previous implementation with a DH parameter with a fixed size.

Since command line client < 10.4.6 doesn't support tls_version parameter, testing
with DHE cipher suite was implemented in mysql_client_test.

- [x] *The Jira issue number for this PR is: MDEV-_____*

## Description
TODO: fill description here

## How can this PR be tested?
TODO: fill steps to reproduce here, if applicable,
      or remove the section

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
TODO: fill details here, if applicable, or remove the section

2021-06-30 20:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=1869) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=1869) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=1869) it.</sub>

2021-07-04 16:55 UTC, vaintroub requested changes
Could you make it compilable,  and pass tests on all platforms (including the Appveyor tests), then squash your commits, so it can be reviewed? BTW, There is no WolfSSL in the version which you decided to have as base for your commit. WolfSSL debuted in 10.4

2021-07-04 16:57 UTC, vaintroub commented
![image](https://user-images.githubusercontent.com/1708204/124393195-92099100-dcf9-11eb-8de2-59a5c5d5d813.png)
that needs to be all green

2021-10-04 20:28 UTC, dlenski commented on vio/viosslfactories.c
> +#if !defined(WOLFSSL) && !defined(SSL_CTRL_SET_DH_AUTO)
It appears that `#define SSL_CTRL_SET_DH_AUTO` was added considerably before OpenSSL v1.0.2: https://github.com/openssl/openssl/commit/09599b52d4e295c380512ba39958a11994d63401 ("Auto DH support."), first tagged in https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0-pre1.

Will this feature _actually work_ with OpenSSL >=1.1.0-pre1 < 1.0.2?

Should there additionally be a check for `OPENSSL_VERSION_NUMBER < 0x10200000L`?

2021-10-04 20:29 UTC, dlenski commented on vio/viosslfactories.c
> +#if !defined(SSL_CTRL_SET_DH_AUTO)
Same question [as above](https://github.com/MariaDB/server/pull/1869/files#r721693775) regarding whether or not an explicit check for OpenSSL >=1.0.2 is needed.

2021-11-26 15:45 UTC, vaintroub commented
@9EOR9 , this needs to pass on CI, before it can be reviewed. apparently, something is weird about Windows, as you can see from Appveyor output

2021-11-26 15:47 UTC, vaintroub requested changes
as commented earlier, this needs to be tested also on 10.4, and pass CI on Windows.
I think 10.4 as target should be fine, 10.2/3 are old and, we might not want to mess up with yassl compatibility.

2022-08-25 14:35 UTC, LinuxJedi commented
Hi @9EOR9,

This appears to have been resolved elsewhere in 10.8.1 as part of [MDEV-25785](https://jira.mariadb.org/browse/MDEV-25785). Is it OK to close this PR now?

2022-09-23 10:40 UTC, LinuxJedi commented
As my previous comment I will close this for now. Please feel free to reopen if you feel this is in error.

2022-09-23 10:40 UTC, closed without merging