Improve documentation of json parser functions
MariaDB/server pull request #1876
Opened 2021-07-21 07:29 UTC by idoqo

Signed-off-by: Michael Okoko <okokomichaels@outlook.com>

## Description
I had to work with some of the JSON parser functions while working on MDEV-21130. They were helpful but also, the comments could be improved. This tries to make it clearer e.g., 
- by describing how to get desired values after calling `json_get_array_item`

2021-07-21 10:52 UTC, ericherman approved these changes

2021-07-21 13:04 UTC, KartikSoneji requested changes
The functions are called `json_*` instead of `js_*` everywhere else.

Can you please fix this line as well? GitHub doesn't allow changing lines that haven't been touched by the original PR.
https://github.com/MariaDB/server/blob/274534d82af9aae851f4a3c64aea7c03648b988c/include/mysql/service_json.h#L41

2021-07-22 00:10 UTC, KartikSoneji approved these changes

2021-07-22 07:13 UTC, cvicentiu commented
Hi @idoqo!

Can you please rebase your changes on top of 10.4 branch, as that's where the typos were initially introduced. Also, please squash the 2 commits into 1.

I'll merge the PR once you've done that.

2021-07-22 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=1876) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=1876) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: idoqo<br/>:white_check_mark: nayuta-yanagisawa<br/>:x: vaintroub<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=1876) it.</sub>

2021-07-22 11:50 UTC, idoqo commented
I've rebased and changed the base branch to 10.4 - though not sure why AppVeyor reports it as non-mergeable at the moment (git doesn't seem to complain of conflicts).

2021-07-22 18:51 UTC, merged