MDEV-26674: Set innodb_use_native_aio=OFF when using io_uring on a potentially affected kernel
MariaDB/server pull request #1953
Opened 2021-11-23 00:41 UTC by grooverdan

This appends 1193a793c40b806c6f1f007bbd87f4d9a73e686d to include the
stable kernel versions between 5.10 and 5.16.

5.15.3 includes the kernel fix https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.15.3
5.14.19 includes the kernel fix https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.14.19

To confirm the previous assumption that 5.16 is going to be fixed
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?h=v5.16-rc1&id=d3e3c102d107bb84251455a298cf475f24bab995
is the applicable commit.

Tested:
```
$ uname -r
5.14.20-200.fc34.x86_64
$ mariadblocal
Installing MariaDB/MySQL system tables in '/tmp/build-mariadb-server-10.6-datadir' ...
2021-11-23 11:37:23 0 [Note] /home/dan/repos/build-mariadb-server-10.6/sql/mysqld (server 10.6.6-MariaDB) starting as process 3805 ...
2021-11-23 11:37:23 0 [Note] InnoDB: The first data file './ibdata1' did not exist. A new tablespace will be created!
2021-11-23 11:37:23 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-11-23 11:37:23 0 [Note] InnoDB: Number of pools: 1
2021-11-23 11:37:23 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-11-23 11:37:23 0 [Note] InnoDB: Using liburing
2021-11-23 11:37:23 0 [Note] InnoDB: Initializing buffer pool, total size = 134217728, chunk size = 134217728
...

$ mc -e 'show global variables like "%aio"'
+-----------------------+-------+
| Variable_name         | Value |
+-----------------------+-------+
| innodb_use_native_aio | ON    |
+-----------------------+-------+
```

2021-11-23 09:29 UTC, dr-m requested changes
On my Debian GNU/Linux system, the `utsname::release` would only contain a short name, such as `5.15.0-4-amd64`, while the `utsname::version` would contain the actual minor version number, such as `5.14.16`. Did you check my preliminary patch in [a comment of mine](https://jira.mariadb.org/browse/MDEV-26674?focusedCommentId=203649&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-203649) to [MDEV-26674](https://jira.mariadb.org/browse/MDEV-26674)? The version numbers are incorrect, but think that the general idea should be fine:
```diff
diff --git a/storage/innobase/handler/ha_innodb.cc b/storage/innobase/handler/ha_innodb.cc
index 72db9df0346..83c163adf23 100644
--- a/storage/innobase/handler/ha_innodb.cc
+++ b/storage/innobase/handler/ha_innodb.cc
@@ -19416,9 +19416,15 @@ static bool innodb_use_native_aio_default()
 #ifdef HAVE_URING
   utsname &u= uname_for_io_uring;
   if (!uname(&u) && u.release[0] == '5' && u.release[1] == '.' &&
-      u.release[2] == '1' && u.release[3] > '0' && u.release[3] < '6')
+      u.release[2] == '1' && u.release[3] > '0' && u.release[3] < '5' &&
+      u.release[4] == '.')
   {
-    io_uring_may_be_unsafe= u.release;
+    /* io_uring() in some Linux kernels 5.11 to 5.14 may hang. */
+    if (u.release[3] == '4')
+      if (const char *s= strstr(u.version, "5.14."))
+        if ((s[5] > '1' && s[6] >= '0') || (s[5] == '1' && s[6] >= '4'))
+          return true; /* 5.14.14 and later should be fine */
+    io_uring_may_be_unsafe= u.version;
     return false; /* working around io_uring hangs (MDEV-26674) */
   }
 #endif
```
I would suggest the following logic for disabling `innodb_use_native_aio` by default:
* 5.11 through 5.13 (I suppose these are not LTS releases).
* 5.14.0 through 5.14.x that contains all fixes. I think that 5.14.16 can still hang.
* 5.15.0 through 5.15.3.

It looks like Debian Unstable shipped 5.15.3 as `linux-image-5.15.0-1-amd64`. I have installed that kernel, so I can easily check if it is fine.

2021-11-23 10:31 UTC, vaintroub commented
I'd suggest some sscanf   %d.%d.%d (or even C++ iostream)parsing, and a macro to compare the 3-component versions lexicographically,   for better readability

2021-11-23 12:40 UTC, dr-m commented
@grooverdan Can you please test if d84d1ad68636daed43669db9018aff239075be45 works for you? I am relying on your word that 5.14.19 is fine, because it is not yet available in a Debian package. I successfully tested 5.15.3.

2021-11-24 03:27 UTC, grooverdan commented
Fedora version isn't populated the same way (it looks a little mad).
```
(gdb) p uname_for_io_uring
$2 = {sysname = "Linux", '\000' <repeats 59 times>, nodename = "localhost.localdomain", '\000' <repeats 43 times>, release = "5.14.20-200.fc34.x86_64", '\000' <repeats 41 times>, version = "#1 SMP Thu Nov 18 22:03:20 UTC 2021", '\000' <repeats 29 times>, machine = "x86_64", '\000' <repeats 58 times>, domainname = "(none)", '\000' <repeats 58 times>}
```

> I am relying on your word that 5.14.19 is fine

Tested 5.14.20 with [reproduction of bug](https://bugzilla.redhat.com/show_bug.cgi?id=2018882#c3). 5.14.19 change log links in jira references the fixed commit.

Modified to - f46352fd9bb3817ac8253c6e21216c64bf65bee7

2021-11-24 06:57 UTC, dr-m commented
Thank you. I posted some suggestions to f46352fd9bb3817ac8253c6e21216c64bf65bee7. I think that we’d better wait for 5.14.21 where this has hopefully been fixed. We still have a couple of months until the scheduled mariadb-5.6.6 release.

2021-11-25 07:04 UTC, closed without merging

2021-11-25 07:11 UTC, dr-m commented
@grooverdan pushed de7db5517de11a58d57d2a41d0bc6f38b6f92dd8, relaxing the original work-around 1193a793c40b806c6f1f007bbd87f4d9a73e686d by restricting it to kernel versions 5.11.0 through 5.15.2. The original work-around had changed the default to `innodb_use_native_aio=OFF` on all 5.15.x kernels.

It is unclear whether this bug was fixed in 5.14.21 (the last in that kernel series). Some Linux distributions may backport the fix to their versions of 5.11 through 5.14, but it is simplest that we retain the safe default. Users of those kernels may explicitly enable `innodb_use_native_aio=ON` to override our work-around.