MDEV-28011 deb autobake static dependencies
MariaDB/server pull request #2056
Opened 2022-03-18 06:56 UTC by grooverdan

- [x] *The Jira issue number for this PR is: MDEV-28011*

## Description

like #2055

## How can this PR be tested?

https://salsa.debian.org/mariadb-team/mariadb-server/-/merge_requests/9

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ X ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility

2022-03-18 10:53 UTC, illuusio commented
What do you mean with static dependencies?

2022-03-18 15:28 UTC, ottok commented
Good catch riscv64 also supports pmem now! I will test that downstream Debian next week.

2022-03-24 06:03 UTC, ottok requested changes

2022-03-24 06:03 UTC, ottok commented on debian/autobake-deb.sh
> +  bullseye|bookworm)
For the time being, bookworm=sid and should just work out-of-the-box.

I still think using `apt-cache madison` was a good system and apt-cache to my knowledge always works if the build host is healthy.

2022-03-24 06:03 UTC, ottok commented on debian/autobake-deb.sh
> +    if [[ ! "$architecture" =~ amd64|arm64|ppc64el ]]
Latest version of this PR no longer has riscv64 here, so I assume it didn't work on that arch.

2022-03-24 06:05 UTC, ottok commented
The branch on Debian Salsa: https://salsa.debian.org/grooverdan/mariadb-server/-/tree/10.6-MDEV-28011-test-pmem-autobake
Salsa-CI passes on everything apart from the build-all/build-any cross-build tests, but that is unrelated.

2022-03-24 06:08 UTC, ottok commented
Looking at https://buildd.debian.org/status/package.php?p=pmdk riscv64 is supported, so I will test that in next Debian upload of mariadb-10.6.

2022-03-24 08:03 UTC, ottok commented
> apt-cache madison was decent, but we don't build with hosts any more, only containers. Clearing cache on containers is pretty standard.

Sure you can clean the apt cache but you need to load it anyway before installing anything (e.g. `apt update`), otherwise apt will not work at all, hence `apt-cache madison` will always work if `apt install` works and builder is healthy.

2022-03-25 03:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2056) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2056) before we can accept your contribution.<br/>**2** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: ottok<br/>:white_check_mark: grooverdan<br/>:x: dr-m<br/>:x: vuvova<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2056) it.</sub>

2022-03-25 03:42 UTC, merged

2022-03-25 03:43 UTC, grooverdan commented
closed via 1b2ee693b7cf2f514fa93c3acc047d4328b96364
also added pmem on riscv64 63f76d3b98ea5bc829c0bc08830ec3a9267915c4

2022-03-26 22:34 UTC, ottok commented
My review feedback was "request changes" - those were ignored and instead multiple extra commits added and then merged straight away. This isn't how I would expect a Pull Request review to go.