MDEV-15718: check for exact mysqld process
MariaDB/server pull request #2068
Opened 2022-03-25 12:53 UTC by fauust

## Description

Debian dpkg preinst checks if mysql is running using `pgrep` and we can have other processes running containing 'mysqld' for  instance `prometheus/mysqld_exporter`.

## How can this PR be tested?

This is a rare case where another process running contains `mysqld` in it's name. In that case `pgrep` will return program's pid even if mysqld is stopped.

2022-03-26 22:20 UTC, ottok requested changes
While working on #2069 you probably noticed we already have this?

@vuvova did it in https://github.com/MariaDB/server/commit/c9f0f88838f895dce7b9596ba298fb8116c4fd2c

± grep -F 'pgrep' debian/*
debian/mariadb-server-10.6.postrm:    if ! pgrep -x mariadbd > /dev/null; then return; fi
debian/mariadb-server-10.6.postrm:    if ! pgrep -x mysqld > /dev/null; then return; fi
debian/mariadb-server-10.6.preinst:    if ! pgrep -x --ns $$ mariadbd > /dev/null; then return; fi
debian/mariadb-server-10.6.preinst:    if ! pgrep -x --ns $$ mysqld > /dev/null; then return; fi

If you make a new commit it will cause extra work to mergers to figure out that there is conflict but with no changes. Just cherry-pick https://github.com/MariaDB/server/commit/c9f0f88838f895dce7b9596ba298fb8116c4fd2c on the 10.2 branch if that is a valid thing to do (but didn't 10.2 support already end?).

2022-03-27 17:50 UTC, fauust commented
> While working on #2069 you probably noticed we already have this?
> 
> @vuvova did it in [c9f0f88](https://github.com/MariaDB/server/commit/c9f0f88838f895dce7b9596ba298fb8116c4fd2c)

This commit is missing the namespace fix `--ns` (docker).

> If you make a new commit it will cause extra work to mergers to figure out that there is conflict but with no changes. Just cherry-pick [c9f0f88](https://github.com/MariaDB/server/commit/c9f0f88838f895dce7b9596ba298fb8116c4fd2c) on the 10.2 branch if that is a valid thing to do (but didn't 10.2 support already end?).

10.2 should be supported until May 22 (https://mariadb.org/mariadb-55-rip/).

2022-03-29 07:06 UTC, illuusio commented
As this fixes JIRA bug I don't see problem here. It's fixed upstream but 10.3 does not have fix.

2022-03-30 06:00 UTC, ottok approved these changes
An ideal commit message would mention the commits and branches where this was already done, so that whoever merges this can immediately read and understand why the merge is empty when hitting branch 10.x.

Even better we would not make a new git commit but just cherry-pick the original one on 10.2. Approving that and alternatively if merging this PR as fall-back if cherry-picking does not work.

2022-03-30 15:36 UTC, fauust commented
> An ideal commit message would mention the commits and branches where this was already done, so that whoever merges this can immediately read and understand why the merge is empty when hitting branch 10.x.

Done.

> Even better we would not make a new git commit but just cherry-pick the original one on 10.2. Approving that and alternatively if merging this PR as fall-back if cherry-picking does not work.

Ok but as said earlier, this fix is a combination of fb7c1b9415c9a8b0dc2e86ae44f0e7a2634e5d7e and c9f0f88838f895dce7b9596ba298fb8116c4fd2c so I am not sure how to handle this with cherry-pick? If it's possible then I will appreciate if you can give me the exact git commands to accomplish such a thing.

2022-05-04 06:59 UTC, ottok requested changes
This was superseded by #2076 and should not be merged

2022-05-04 08:34 UTC, an3l commented
Closing this PR, pushed with https://github.com/MariaDB/server/commit/794bebf9ee18de4138c4d2c93853d49ff3af7f12

2022-05-04 08:34 UTC, closed without merging