MDEV-28379: Remove libfmt-dev requirement when building buster-backports
MariaDB/server pull request #2103
Opened 2022-04-22 09:12 UTC by illuusio

- [x] *The Jira issue number for this PR is: MDEV-28379*

## Description
Buster-backports only have libfmt-dev version 6.0 and MariaDB requires libfmt-dev version 7.0. If it's not provided CMake will handle download and it will be build during compilation. **This should not be done no where else than using Buster Backports.**

So this fixes problem:
```
The following packages have unmet dependencies:
 builddeps:. : Depends: libfmt-dev (>= 7.0.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

## How can this PR be tested?
This one can be tested on Debian Buster Image with enabled backports repository.
Salsa-CI run this one is from here:
https://salsa.debian.org/illuusio/mariadb-server/-/jobs/2689802/raw
Currently it fails because lack of space which should be investigated later on.

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
More testing is more backward compatibility

2022-04-30 20:29 UTC, ottok commented
This is not rendering properly since you use a wildcard character instead of a cross:
![image](https://user-images.githubusercontent.com/668724/166121559-35106d87-2db4-4a06-8554-94da461b537f.png)

2022-04-30 20:34 UTC, ottok requested changes
The buster-backports build on Salsa-CI is supposed to simulate the buster-backports build. If the source has been modified and has a new compulsory requirement that cannot be satisfied on buster-backports, then the build **should fail**.

It is OK to do backporting hacks on-the-fly in `autobake-deb.sh` as it only runs on MariaDB.org builders and can do whatever you want, but the real native Debian buster-backports *can not* have such hacks in the CI script. If the modification cannot be done in the packaging proper, then it can't be done. Doing something extra in CI phase would only mask that the thing is broken, so don't do it.

Rather, remove the whole buster-backports build or comment it out saying that it can't be enabled unless libfmt-dev 7.0+ enters Buster(-backports).

2022-04-30 20:36 UTC, ottok commented
Oh yeah, this line is right before `- *autobake-deb-steps`. So it does run autobake-deb.sh here. Thus the correct place for such a customization is inside the actual `autobake-deb.sh` and should solve this issue.

2022-04-30 20:39 UTC, ottok commented
Hmm.. The two backport stages are currently inconsistent in their contents. One extend the build, and the other extends the normal build + refers to autobake-deb.sh (inherited from original https://github.com/MariaDB/server/commit/03119c589026f9a8f499255291624f71ba2e9e04). This should be unified.

2022-05-03 06:03 UTC, illuusio commented
Yes I have been planning to do some Salsa-CI work after BB work. Those Distro update test should be worked together as there is several similar code repeating but this not the point of this PR.

2022-05-03 15:31 UTC, ottok commented
I tried to make 10.9 all green on Salsa-CI in https://salsa.debian.org/mariadb-team/mariadb-server/-/commits/10.9-salsa-ci, and plan to finalize it in coming days if I have extra time.

2022-05-04 07:10 UTC, ottok commented
> I tried to make 10.9 all green on Salsa-CI in https://salsa.debian.org/mariadb-team/mariadb-server/-/commits/10.9-salsa-ci, and plan to finalize it in coming days if I have extra time.

Filed now as #2112.

2022-05-04 07:30 UTC, illuusio commented
Ok I'll see #2112 and test it on Salsa-CI.. If it's good th

> > I tried to make 10.9 all green on Salsa-CI in https://salsa.debian.org/mariadb-team/mariadb-server/-/commits/10.9-salsa-ci, and plan to finalize it in coming days if I have extra time.
> 
> Filed now as #2112.

Good one.. I'll test it too on Salsa-CI and if it's good then just i'll just close this one.

2022-05-05 02:07 UTC, grooverdan commented
assuming closing based on #2112

2022-05-05 02:07 UTC, closed without merging