MDEV-14642 Disallow user to exchange partition with different ROW_FORMAT
MariaDB/server pull request #2116
Opened 2022-05-14 06:12 UTC by TakeKiyo

- [x] *The Jira issue number for this PR is: MDEV-14642*

## Description
MDEV-14642 Disallow user to exchange partition with different ROW_FORMAT

When trying to execute `ALTER TABLE EXCHANGE PARTITION` with different `ROW_FORMAT`, 
assertion `table->s->db_create_options == part_table->s->db_create_options` failed in compare_table_with_partition.
However, this execution should not be allowed.

No MariaDB document about exchange partition were found, however, I found [MySQL document about exchange partition](https://dev.mysql.com/doc/refman/5.7/en/partitioning-management-exchange.html) which says 
>  Table nt is not itself partitioned.
 Table nt is not a temporary table.
 The structures of tables pt and nt are otherwise identical.

This pull request disallow user to exchange partition with different ROW_FORMAT by returning appropriate error instead of assertion failure. 

## How can this PR be tested?
Test case is included in this pull request. 
I add test code to `mysql/main/partition_exchange.test` since similar test code are written in this file. 

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

2022-05-14 12:22 UTC, nayuta-yanagisawa commented
@TakeKiyo Thank you for the pull request. We will review it soon.

2022-05-14 12:32 UTC, nayuta-yanagisawa requested changes
I will check the technical details later, but I have some comments on the commit message.

* The first line of the commit message should be exactly same as the issue title.
* Please make it more descriptive (what is the problem? how to fix? etc.). More precisely, could you include what you wrote in the issue description without referencing the external document.

2022-05-15 03:23 UTC, TakeKiyo commented
@nayuta-yanagisawa 
Thank you for your quick comment.
I modified the commit message based on your comment.

2022-05-15 08:09 UTC, nayuta-yanagisawa commented
Pushed to bb branch: https://github.com/MariaDB/server/commit/99b90d97b0d33852117ef0c0e04ddce0f602042c

2022-05-15 08:22 UTC, nayuta-yanagisawa commented
Just a minor comment but, in the general convention of git, you should properly insert the new lines to the body of the commit message. Please check other commits of the repository.

2022-05-15 11:19 UTC, TakeKiyo commented
I rebased and modified the commit message.
Thank you for your comment.

2022-05-16 07:29 UTC, nayuta-yanagisawa submitted a review, later dismissed

2022-05-16 09:16 UTC, nayuta-yanagisawa commented
The following test case passes and thus the problem seems to be Arira/MyISAM specific:

```
--source include/have_partition.inc
--
--source include/have_innodb.inc
 
CREATE TABLE t1 (i INT NOT NULL, KEY (i)) ENGINE=InnoDB ROW_FORMAT=REDUNDANT PARTITION BY KEY(i) PARTITIONS 2;
CREATE TABLE t2 (i INT NOT NULL, KEY (i)) ENGINE=InnoDB;
--error ER_PARTITION_EXCHANGE_DIFFERENT_OPTION
ALTER TABLE t1 EXCHANGE PARTITION p1 WITH TABLE t2;
 
# Cleanup
DROP TABLE t1, t2;
```

2022-05-16 14:38 UTC, nayuta-yanagisawa commented
I wrote down my analysis to https://jira.mariadb.org/browse/MDEV-14642. I'm now thinking of how the assertion error should be fixed. Please wait for a while.

2022-05-18 08:14 UTC, nayuta-yanagisawa requested changes
@TakeKiyo After a private discussion with @holyfoot , I now think that the fix is mostly OK while I still have some comments.

2022-05-18 08:14 UTC, nayuta-yanagisawa commented on mysql-test/main/partition_exchange.test
> +--echo # Test exchange partition with different ROW_FORMAT
Explicitly mention the issue ID and title.

```
--echo #
--echo # MDEV-14642 Assertion `table->s->db_create_options == part_table->s->db_create_options' failed in compare_table_with_partition
--echo #
```

2022-05-18 08:14 UTC, nayuta-yanagisawa commented on mysql-test/main/partition_exchange.test
> +DROP TABLE t1, t2;
Add the following test case, which is a simplified version of one provided by Roel:

```
CREATE TABLE t1 (a INT, PRIMARY KEY(a)) ENGINE=InnoDB PARTITION BY KEY(a) PARTITIONS 2;
CREATE TABLE t2 (a INT, PRIMARY KEY(a)) CHECKSUM=1, ENGINE=InnoDB;
ALTER TABLE t1 EXCHANGE PARTITION p0 WITH TABLE t2;
 
# Cleanup
DROP TABLE t1, t2;
```

2022-05-18 12:57 UTC, TakeKiyo commented
@nayuta-yanagisawa 
I modified the code based on your comment.

Thank you for your kind guidance.
I didn't understand the whole analysis, so I will take my time to understand it.

2022-05-18 14:06 UTC, nayuta-yanagisawa commented on sql/sql_partition_admin.cc
> +  if (table->s->db_create_options != part_table->s->db_create_options)
Unnecessary space at the end of the line

2022-05-18 14:06 UTC, nayuta-yanagisawa commented on mysql-test/main/partition_exchange.test
> +
Unnecessary space

2022-05-18 14:06 UTC, nayuta-yanagisawa commented on mysql-test/main/partition_exchange.test
> +
Unnecessary space

2022-05-18 14:09 UTC, nayuta-yanagisawa commented
I pushed the commit to bb again: https://github.com/MariaDB/server/commit/9eb701ccf14e959e400a30e4c89b4c4353519879

2022-05-18 14:22 UTC, TakeKiyo commented
@nayuta-yanagisawa 
I deleted some unnecessary spaces and pushed again. 

I couldn't notice the unnecessary space, do you use some tools to check the code?

2022-05-18 14:24 UTC, nayuta-yanagisawa commented
@TakeKiyo I found them just by `git diff HEAD^`. `git` marks such unnecessary white spaces by red color.

2022-05-18 14:29 UTC, TakeKiyo commented
@nayuta-yanagisawa 
Thank you.
I will check carefully before creating pr from now on.

2022-05-18 14:38 UTC, merged