MDEV-28645: Reword MariaDB 10.9 Salsa-CI file and add upgrade test from 10.8
MariaDB/server pull request #2133
Opened 2022-05-24 10:03 UTC by illuusio

- [x] *The Jira issue number for this PR is: MDEV-28645*

## Description
Currently Salsa-CI upgrade topic are bit misleading and incorrect. This PR correct them and adds upgrade test from 10.8

## How can this PR be tested?
Check upgrading topics on Salsa-CI run:
https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/384409

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
Nothing this more linting than anything. Does not change behavior or adds more as 10.8 upgrading is tested.

2022-05-25 04:13 UTC, ottok requested changes
Thanks! Adding a test for upgrades of 10.8 is useful, and unifying naming scheme is a good cleanup to do.

However, using `mariadb.org-10.7 to mariadb 10.9 upgrade:` would mean that when merging Salsa-CI changes across versions we would need to keep bumping that `10.9` and the time? And this test always runs on a specific branch, so maybe mentioning the target name is redundant? How about using a naming scheme like `upgrade from mariadb.org-10.7:`? Then we don't need to name the target, as the target is always the commit in question. Or even simpler, just call it `upgrade mariadb.org-10.7:`?

We should think this through as once we do this change, we should do the same change everywhere to unify the naming, and we don't want to flip the name back and forth.

Tangenting the cleanup, lines like 'service mariadb status # There is no init.d/mysql in MariaDB 10.XXX` should always say 'service mariadb status # There is no init.d/mysql in MariaDB 10.5+` and not have the 10.5+ change on merges on newer branches, as the comment is about MariaDB release changes, not any branch specific stuff.

Diff of current [10.6 Salsa-CI in Debian](https://salsa.debian.org/mariadb-team/mariadb-server/-/blob/debian/latest/debian/salsa-ci.yml) vs upstream MariaDB/server: https://paste.ubuntu.com/p/GR832ZHbPK/

2022-05-31 09:35 UTC, illuusio commented
Made suggested changes and add test for 10.9. Salsa-CI pipeline can be found on:
https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/384409
Also updated to description

2022-07-19 06:14 UTC, ottok approved these changes
LGTM!

2022-09-07 11:00 UTC, LinuxJedi approved these changes
No objection here, many thanks.

Not sure if it is possible, but it would be nice if this could be made into some kind of building block rather than copy/paste for each release. A bit like Jenkins Job Builder. But this is out of scope for this PR/ticket.

2022-09-07 11:23 UTC, merged