WIP: MDEV-28795 Deprecate spider_param_bka_table_name_type
MariaDB/server pull request #2167
Opened 2022-06-20 17:21 UTC by chansuke

- [x] *The Jira issue number for this PR is: MDEV-28795

## Description
Deprecate spider_param_bka_table_name_type

## How can this PR be tested?
WIP: My working PC is too week and suddenly hangout during the test. So I will try again in an another environment.

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

2022-06-22 05:23 UTC, nayuta-yanagisawa requested changes
The test regarding the deprecated variable failed. I think that the variable name should be `spider_bka_table_name_type` not `spider_param_bka_table_name_type`.

This was my bad because the issue title itself was wrong. However, it would be great if you  could run the test case locally. Then, you would have more chances to find errors.

```
> ./mysql-test/mtr spider.variable_deprecation
Logging: /home/nayuta_mariadb/repo/mariadb-server/10.7/mysql-test/mariadb-test-run.pl  spider.variable_deprecation
VS config: 
vardir: /home/nayuta_mariadb/repo/mariadb-server/10.7/bld/mysql-test/var
Checking leftover processes...
Removing old var directory...
Creating var directory '/home/nayuta_mariadb/repo/mariadb-server/10.7/bld/mysql-test/var'...
Checking supported features...
MariaDB Version 10.7.5-MariaDB-debug
 - SSL connections supported
 - binaries are debug compiled
 - binaries built with wsrep patch
Collecting tests...
Installing system database...

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
spider.variable_deprecation              [ fail ]
        Test ended at 2022-06-22 14:18:41

CURRENT_TEST: spider.variable_deprecation
mysqltest: At line 130: query 'SET spider_param_bka_table_name_type = 1' failed: ER_UNKNOWN_SYSTEM_VARIABLE (1193): Unknown system variable 'spider_param_bka_table_name_type'

The result from queries just before the failure was:
< snip >
Warning	1287	The table parameter 'buffer_size' is deprecated and will be removed in a future release
DROP TABLE tbl_a;
DROP TABLE tbl_b;
# MDEV-27926 Deprecate spider_init_sql_alloc_size
SET spider_init_sql_alloc_size = 1;
Warnings:
Warning	1287	'@@spider_init_sql_alloc_size' is deprecated and will be removed in a future release
SHOW VARIABLES LIKE "spider_init_sql_alloc_size";
Variable_name	Value
spider_init_sql_alloc_size	1
CREATE TABLE tbl_a (a INT) ENGINE=Spider COMMENT='isa "1"';
Warnings:
Warning	1287	The table parameter 'isa' is deprecated and will be removed in a future release
CREATE TABLE tbl_b (a INT) ENGINE=Spider COMMENT='init_sql_alloc_size "1"';
Warnings:
Warning	1287	The table parameter 'init_sql_alloc_size' is deprecated and will be removed in a future release
DROP TABLE tbl_a;
DROP TABLE tbl_b;
# MDEV-28795 Deprecate spider_param_bka_table_name_type
SET spider_param_bka_table_name_type = 1;

More results from queries before failure can be found in /home/nayuta_mariadb/repo/mariadb-server/10.7/bld/mysql-test/var/log/variable_deprecation.log

 - saving '/home/nayuta_mariadb/repo/mariadb-server/10.7/bld/mysql-test/var/log/spider.variable_deprecation/' to '/home/nayuta_mariadb/repo/mariadb-server/10.7/bld/mysql-test/var/log/spider.variable_deprecation/'
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 3 seconds executing testcases

Failure: Failed 1/1 tests, 0.00% were successful.

Failing test(s): spider.variable_deprecation

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

mysql-test-run: *** ERROR: there were failing test cases
```

2022-07-22 05:33 UTC, nayuta-yanagisawa commented
The test is still failing...

```
> ./mysql-test/mtr spider.variable_deprecation
Logging: /home/nayuta_mariadb/repo/mariadb-server/10.10/mysql-test/mariadb-test-run.pl  spider.variable_deprecation
VS config: 
vardir: /home/nayuta_mariadb/repo/mariadb-server/10.10/bld/mysql-test/var
Checking leftover processes...
Removing old var directory...
Creating var directory '/home/nayuta_mariadb/repo/mariadb-server/10.10/bld/mysql-test/var'...
Checking supported features...
MariaDB Version 10.7.5-MariaDB-debug
 - SSL connections supported
 - binaries are debug compiled
 - binaries built with wsrep patch
Collecting tests...
Installing system database...

==============================================================================

TEST                                      RESULT   TIME (ms) or COMMENT
--------------------------------------------------------------------------

worker[1] Using MTR_BUILD_THREAD 300, with reserved ports 16000..16019
spider.variable_deprecation              [ fail ]
        Test ended at 2022-07-22 14:32:59

CURRENT_TEST: spider.variable_deprecation
mysqltest: At line 146: query 'CREATE TABLE tbl_a (a INT) $MASTER_1_ENGINE COMMENT='btt "1"'' failed: ER_TABLE_EXISTS_ERROR (1050): Table 'tbl_a' already exists

The result from queries just before the failure was:
< snip >
SET spider_semi_table_lock_connection = 0;
Warnings:
Warning	1287	'@@spider_semi_table_lock_connection' is deprecated and will be removed in a future release
SHOW VARIABLES LIKE "spider_semi_table_lock_connection";
Variable_name	Value
spider_semi_table_lock_connection	0
CREATE TABLE tbl_a (a INT) ENGINE=Spider COMMENT='stc "0"';
Warnings:
Warning	1287	The table parameter 'stc' is deprecated and will be removed in a future release
CREATE TABLE tbl_b (a INT) ENGINE=Spider COMMENT='semi_table_lock_connection "0"';
Warnings:
Warning	1287	The table parameter 'semi_table_lock_connection' is deprecated and will be removed in a future release
# MDEV-28795 Deprecate spider_bka_table_name_type
SET spider_bka_table_name_type = 1;
Warnings:
Warning	1287	'@@spider_bka_table_name_type' is deprecated and will be removed in a future release
SHOW VARIABLES LIKE "spider_bka_table_name_type";
Variable_name	Value
spider_bka_table_name_type	1
CREATE TABLE tbl_a (a INT) ENGINE=Spider COMMENT='btt "1"';

More results from queries before failure can be found in /home/nayuta_mariadb/repo/mariadb-server/10.10/bld/mysql-test/var/log/variable_deprecation.log

 - saving '/home/nayuta_mariadb/repo/mariadb-server/10.10/bld/mysql-test/var/log/spider.variable_deprecation/' to '/home/nayuta_mariadb/repo/mariadb-server/10.10/bld/mysql-test/var/log/spider.variable_deprecation/'
--------------------------------------------------------------------------
The servers were restarted 0 times
Spent 0.000 of 3 seconds executing testcases

Failure: Failed 1/1 tests, 0.00% were successful.

Failing test(s): spider.variable_deprecation

The log files in var/log may give you some hint of what went wrong.

If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html

mysql-test-run: *** ERROR: there were failing test cases
```

2022-07-22 13:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2167) before we can accept your contribution.<br/>**1** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: chansuke<br/>:x: sanja-byelkin<br/>:x: montywi<br/>:x: abarkov<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2167) it.</sub>

2022-07-22 16:26 UTC, chansuke commented
@nayuta-yanagisawa I appreciate your review and sorry for my poor commit. I was kept cloning and building latest `10.7` branch for test and just running `./mysql-test/mtr` and  my changes was not included. Now I cloned my branch and debug build and tested with `./mysql-test/mtr spider.variable_deprecation` and it says `Completed: All 1 tests were successful.`. Thanks so much for your help.

2022-07-25 00:32 UTC, nayuta-yanagisawa approved these changes

2022-07-25 00:33 UTC, merged