MDEV-28926 Add time spent on query optimizer to JSON ANALYZE
MariaDB/server pull request #2187
Opened 2022-07-14 09:56 UTC by mariadb-LuisLizardo

- [x] *The Jira issue number for this PR is: MDEV-28926*

## Description
ANALYZE FORMAT=JSON does not show the time spent doing query optimization. This PR adds it with the following format: 

```
"query_optimization": {  "r_total_time_ms": NNNN.NNN }
```

The query optimization time is measured between the calls to `Explain_query::Explain_query()` and `Explain_query::query_plan_ready()`.

With this PR, the ANALYZE FORMAT=JSON output will become: 

```
MariaDB [j1]> show analyze format=json for 6;
--
{
   "r_query_time_in_progress_ms": 60499,
   "query_optimization": {
      "r_total_time_ms": "NNNN.NNN"
   },
   "query_block": {
      "select_id": 1,
      "r_loops": 1,
      "nested_loop": [
         {
            "table": {
               "table_name": "t1",
               "access_type": "ALL",
               "r_loops": 1,
               "rows": 1000,
               "r_rows": 1,
               "r_table_time_ms": 0.156016501,
               "r_other_time_ms": 0,
               "filtered": 100,
               "r_filtered": 100,
               "attached_condition": "t1.a <= 3"
            }
         }
      ]
   }
}
```

Besides that, this PR improves `Explain_query::print_explain_json()` quality by adding more modularity and verbose names.
Fix the problem of the writer being left open when no query plans were found.   

## How can this PR be tested?

Test cases at `mysql-test/` were adapted to include the new JSON element. These tests covered all changes. 

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

2022-07-14 09:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2187) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2187) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2187) it.</sub>

2022-07-18 09:37 UTC, spetrunia commented
Generally, looks ok.  
There are a few fixes that need to be made:
* Please address the comments in the review.
* Please make all changes be in one patch.
Please push into branch named `bb-10.10-mdev28926`.  (the `bb-` part is important so that CI will pick it up).

2022-07-18 09:37 UTC, spetrunia requested changes
The changes needed in the patch

2022-07-18 09:37 UTC, spetrunia commented on sql/sql_explain.h
> +  Exec_time_tracker query_optimization_total_time_tracker;
This is a very long name. Please change for a shorter one, `optimization_time_tracker`.

2022-07-18 09:37 UTC, spetrunia commented on sql/sql_explain.cc
> +  bool were_query_plans_found = print_query_blocks_json(&writer, is_analyze, is_show_cmd);
Also a very long name. Please change to `plan_found`  (it's singular. there can't be more than one).

2022-07-18 09:37 UTC, spetrunia commented on sql/sql_explain.cc
> +bool Explain_query::print_query_blocks_json(Json_writer *writer, const bool is_analyze, const bool is_show_cmd)
Please keep the lines to be no longer than 80 characters.
(check the code around to see how multi-line code is formatted)

2022-07-18 09:37 UTC, spetrunia commented on sql/sql_explain.cc
> +void Explain_query::send_explain_json_to_output(Json_writer *writer, select_result_sink *output)
The same as above: please make the lines to be no longer than 80 chars. max

2022-07-18 09:37 UTC, spetrunia commented on sql/sql_explain.cc
> +  if(were_query_plans_found){
Coding style: please use space after `if` and put the `{` onto the next line:

```
 if ( )
 {
 ```

2022-07-18 14:15 UTC, mariadb-LuisLizardo commented
@spetrunia what do you mean by one patch? One commit? 

I addressed all the change requests and push it, under the branch `bb-10.10-mdev28926` as you requested. 
For that, i had to open a new PR. https://github.com/MariaDB/server/pull/2193

2022-07-18 14:15 UTC, closed without merging