MDEV-28834: Make minimal Lintian changes and some cleanup
MariaDB/server pull request #2275
Opened 2022-09-21 07:01 UTC by illuusio

- [x] *The Jira issue number for this PR is: MDEV-28834*

## Description
This supersedes PR #2257 which is against 10.6

 * Lintian 2.115 introduced new syntax for overrides. Add minimal set of rules to remove errors and have clean tests. Minimal set of rules can be merge up-to 10.8
 * MariaDB 10.2 is not build for Debian Sid so it can't be used for testing anymore. It should be removed upstream `debian/salsa-ci.yml`
 * Make small change to `debian/rules' to remove one external tab
 * Make sure that there is not versions in external dependency `Conflicts` in `debian/control`

## How can this PR be tested?
Most of these changes are beyond manual testing. Building branch and running lintian against it should work as in Salsa-CI:
https://salsa.debian.org/illuusio/mariadb-server/-/jobs/3264074/raw
Current situation with Lintian is:
https://salsa.debian.org/illuusio/mariadb-server/-/jobs/3258166/raw

There should not be any extra errors marked with `E:`. What comes to removing 10.2 there is nothing to-do because it's just not executed.

Whole run is here and it does not pass as it needs more updating Salsa-CI and Debian packaging control file
https://salsa.debian.org/illuusio/mariadb-server/-/pipelines/426733
But they are not mergable up straight so they should be PRed after this one is in.

## Basing the PR against the correct MariaDB version
- [x] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility
Only backward compatibility change is removing test updating from MariaDB version10.2

2022-10-19 16:09 UTC, ottok commented
I posted now #2294 which fixes the 10.2 upgrade, so there is no need to remove it in a commit in this PR.

2022-10-23 23:49 UTC, ottok commented
The Lintian fixes in this PR together with #2299 makes the Salsa-CI on branch 10.6 almost completely green.

2022-10-24 05:42 UTC, illuusio commented
So I'll probably just close this.

2022-10-25 06:08 UTC, ottok commented
Why did you close this? As I wrote yesterday, this PR and #2299 together are needed to make Salsa-CI pass.

2022-11-20 21:31 UTC, ottok commented
* MDEV-28834: Remove MariaDB version 10.2 upgrade test from Salsa-CI 79d6b33
  * Remove the commit. The justification in the commit messge is simply not true.
* MDEV-28834: Add minimal support for Lintian version 2.115 and above e60bc8c
* MDEV-28834: Add 10.5 specific Lintian 2.115 overrides 2750385
  * Squash these two, they are essentially the same thing, updating the Lintian syntax. Also, does it make sense to add duplicate Lintian lines? Maybe just update the syntax of existing lines instead of adding new lines.
* MDEV-28834: Remove debian/control Replaces version numbers for extern.. 852a293
  * I think these versioned replaces exist for a good reason. The package provides 'libmysqlclient-dev', and thus the relationship needs to be versioned, otherwise it will conflict with itself.
* MDEV-28834: Fix breaks-without-version problem in mariadb-test package 77e8012
  * I don't think we can make these relations versioned. The package provides 'mysql-server' and thus Lintian complains about unversioned relationship to self. Basically the reverse of the 852a293 above. If these are changed, the justification needs to be explained properly. Lintian is not always right, and Lintian errors can't be followed literally. They flag issues that a human needs to understand and resolve.

2022-11-25 17:12 UTC, LinuxJedi requested changes
Based on Otto's review (who is really the subject matter expert here) I'll mark this as requiring changes.

2022-11-28 10:45 UTC, illuusio commented
Ok now they are updated as requested. mostly removed unwanted stuff and meld those two

2022-11-29 09:09 UTC, illuusio commented
There is this Piuparts problem but I assume it's because of missing Changelog entries otherwise this applies minimal Lintian stuff to make sure it won't error on that.

2022-12-05 01:32 UTC, ottok approved these changes
LGTM!

2022-12-08 17:01 UTC, LinuxJedi approved these changes

2022-12-08 17:01 UTC, merged