10.11 innodb wsrep applier lock wait timeout
MariaDB/server pull request #2351
Opened 2022-11-29 17:39 UTC by sjaakola

- [x] *The Jira issue number for this PR is: MDEV-29684*

## Description

This patch implements wsrep applier lock wait timeout
functionality.

As transactions which are executed by appliers have passed
certification in the cluster, they must be applied and committed
successfully. However, occasionally BF aborting local transactions
may not work perfectly due to race conditions or unforeseen
behavior of the lock manager, which may cause appliers to wait
locks indefinitely. Especially if the local transaction has
already reached commit stage, it will not yield via lock
wait timeout.

In order to resolve indefinite applier waits, a short applier
lock wait timeout is introduced. However instead of giving up
with lock wait, a background thread is used to retry BF abort
on behalf of the applier which is waiting for the lock.

A variable to control the applier lock wait timeout is
innodb_wsrep_applier_lock_wait_timeout with default
value of five seconds. If the value is zero, the background
BF aborting is disabled.

The value of innodb_wsrep_applier_lock_wait_timeout is set
to zero in Galera suite MTR test configuration to avoid
non-deterministic behavior.

## How can this PR be tested?
The PR contains a mtr test for testing the functionality

TODO: modify the automated test suite to verify that the PR causes MariaDB to
behave as intended. Consult the documentation on
["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).
In many cases, this will be as simple as modifying one `.test` and one `.result`
file in the `mysql-test/` subdirectory. Without _automated_ tests, future regressions
in the expected behavior can't be automatically detected and verified.

If the changes are not amenable to automated testing, please explain why not and
carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [x ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

## Backward compatibility

2022-11-29 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2351) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2351) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: sjaakola<br/>:x: temeo<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2351) it.</sub>

2022-12-05 08:00 UTC, dr-m requested changes
Please fix the build and test failures.

Because I am concerned about potential performance regressions, I think that this will require extensive performance testing for the case that Galera replication is disabled.

I am confused about the testing status. [MDEV-29684](https://jira.mariadb.org/browse/MDEV-29684) mentions version 10.4, yet this change is targeting 10.11.

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +  my_hrtime_t now{my_hrtime_coarse()};
A non-constant initialization expression for an implicit default constructor is not allowed in the oldest compilers that we support (GCC 4.8.5):
```
/home/buildbot/amd64-centos-7-rpm-autobake/build/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX/storage/innobase/lock/lock0lock.cc:6505:37: error: cannot convert 'my_hrtime_t' to 'ulonglong {aka long long unsigned int}' in initialization
   my_hrtime_t now{my_hrtime_coarse()};
```

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +std::atomic<uint> wsrep_BF_waiting_count;
The variable is not documented by any a comment. Why is it not declared `static`?

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +    ++wsrep_BF_waiting_count;
Why is this using `std::memory_order_seq_cst`?

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +    --wsrep_BF_waiting_count;
Why is this using `std::memory_order_seq_cst`?

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +        trx->reference();
The transaction object should remain valid as long as it is unable to release its locks. The `lock_sys.wait_mutex` that this thread is holding should block that.

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +    ib::warn() << "WSREP watchdog took " << elapsed << " seconds to execute";
Invoking `sql_print_warning()` directly would save at least 5 function calls.

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/lock/lock0lock.cc
> +    trx->release_reference();
Can `trx` be committed or rolled back meanwhile? What would happen in that case?

2022-12-05 08:00 UTC, dr-m commented on storage/innobase/srv/srv0start.cc
> +                }
Why cannot the code be invoked from `srv_master_callback()`?

2022-12-05 08:00 UTC, dr-m commented on mysql-test/suite/galera/t/galera_var_innodb_wsrep_applier_lock_wait_timeout.test
> +CALL mtr.add_suppression("WSREP watchdog took");
Missing newline

2022-12-05 09:58 UTC, janlindstrom commented
This is not exactly related to MDEV-29684 that is a real bug on 10.4. This is more related to https://jira.mariadb.org/browse/MDEV-29496

2025-09-30 09:59 UTC, janlindstrom commented
Closing as rejected.

2025-09-30 09:59 UTC, closed without merging