MDEV-26875: Wrong user in SET DEFAULT ROLE error
MariaDB/server pull request #2362
Opened 2022-12-07 13:19 UTC by an3l

- Regression introduced in https://github.com/MariaDB/server/commit/957cb7b7ba355184aebf0f5dc91b7f2aa620c0e0

Reviewed by: <>

2023-03-30 02:45 UTC, grooverdan commented
`mysql.global_priv` started in 10.4. The regression commit is earlier, so I assume this should be a 10.4 fix.

2023-07-21 07:26 UTC, vuvova requested changes

2023-07-21 07:26 UTC, vuvova commented on sql/sql_acl.cc
> +                          MYF(0), user, host, rolename);
Ok, this is not trivial.

On the first glance this is very wrong.
The situation here: `priv_user@priv_host` tries to set the role `rolename` for the account `user@host`.
The correct error should obviously print `user@host` — that's whom the role cannot be granted to.
The fact that under `--skip-name-resolve` the patch for some reason prints the current user, not the target user, looks like a bug.

But `check_user_can_set_role()` is used in two cases. For `SET DEFAULT ROLE xxx TO yyy`, in that case `host` is never NULL, so it prints the correct error message. And for `SET ROLE xxx`, in that case the current user is always the target user, `host` can be NULL, but printing `priv_user@priv_host` in the error message is not incorrect, it's just confusing.

So, two options here: either add the above explanation here, to clarify why using `priv_host@priv_user` is not a bug in this particular case. Or remove the `if` and use
```c
        /* Role is not granted but current user can see the role */
        my_printf_error(ER_INVALID_ROLE, "User %`s@%`s has not been granted role %`s",
                        MYF(0), user, host ? host : "%", rolename);
```

2023-10-28 07:39 UTC, vuvova approved these changes
ok to push, thanks!

2023-10-30 17:39 UTC, merged