Add remote switch to submodule update for more robust build process
MariaDB/server pull request #2388
Opened 2022-12-20 15:37 UTC by haidong

More recent `git` binary (`2.38.1` and later, possibly even earlier versions) revealed a weakness of MariaDB `submodules.cmake` file. The build fails with the following error:

```
-- Updating submodules
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'wsrep-lib', but it did not contain f8ff2cfdd4c6424ffd96fc53bcc0f2e1d9ffe137. Direct fetching of that commit failed.
CMake Error at cmake/submodules.cmake:47 (MESSAGE):
  No MariaDB Connector/C! Run

      /usr/bin/git submodule update --init --recursive

  Then restart the build.
```

Running `/usr/bin/git submodule update --init --recursive` will not solve the issue.

Following a workaround suggested here[^1]:
```
git config --global protocol.file.allow always
```

the build still fails with the following error. Not to mention this workaround may pose a security risk.

```
-- Updating submodules
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: Fetched in submodule path 'wsrep-lib', but it did not contain f8ff2cfdd4c6424ffd96fc53bcc0f2e1d9ffe137. Direct fetching of that commit failed.
CMake Error at cmake/submodules.cmake:47 (MESSAGE):
  No MariaDB Connector/C! Run

      /usr/bin/git submodule update --init --recursive

  Then restart the build.
```

The proper fix[^2] is to add `--remote` switch to the `submodule update` command[^3] in this commit. This switch ensures that it will not use the superproject's recorded SHA-1 to update the submodule, but will use the status of the submodule's remote-tracking branch instead.

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license.  I am contributing on behalf of my employer Amazon Web Services, Inc.

[^1]: https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html
[^2]: https://stackoverflow.com/a/56621295
[^3]: https://git-scm.com/docs/git-submodule#git-submodule---remote

## How can this PR be tested?
Successful build will confirm that this PR is good.
## Basing the PR against the correct MariaDB version

- [x ] *This is a bug fix and the PR is based against the earliest branch in which the bug can be reproduced*

2022-12-21 02:23 UTC, grooverdan commented
Thanks. Seems to work quite well and helped me recovery from a few broken worktrees that I experienced due to git bisects.

Do you know when `--remote` was added to git?

2022-12-21 03:21 UTC, grooverdan approved these changes

2022-12-21 14:17 UTC, dlenski commented
> Do you know when --remote was added to git?

It was added in 2012, released in Git v1.8.2 (details at https://github.com/git/git/commit/06b1abb5bd38b3cb1972907b059c7f95a197a7a5).

2022-12-21 16:08 UTC, vuvova commented
What does it mean "use the status of the submodule's remote-tracking branch" ?

2022-12-21 16:53 UTC, dlenski commented
@vuvova wrote:

> What does it mean "use the status of the submodule's remote-tracking branch" ?

As you can see from [the commit I linked above](https://github.com/git/git/commit/06b1abb5bd38b3cb1972907b059c7f95a197a7a5), it means that `git submodule update` will do the following to identify the correct commit hash of the submodule:

```sh
cd $SUBMODULE_PATH
git fetch $SUBMODULE_DEFAULT_REMOTE
commit_hash=$(git rev-parse --verify ${SUBMODULE_DEFAULT_REMOTE}/${SUBMODULE_TRACKING_BRANCH})
```

This is in contrast to the default behavior of `git submodule update`, which is to rely on the `commit_hash` recorded _in the superproject_ and to look for that in the submodule. (The default approach causes problems in particular when the submodule's remote has been force-pushed so that the `commit_hash` expected by the superproject is no longer found on the tracked branch.)

If this :point_up: is worth clarifying in the PR/commit, perhaps @haidong can update it.

2022-12-21 17:06 UTC, haidong commented
Thanks @dlenski . You explained better than I could. I'll update the commit message with your comments and push again.

2022-12-21 17:26 UTC, vuvova commented
Hm. Our submodules don't really *follow branches*. Newer commit might not necessarily work, so automatically picking a newer commit is strictly speaking incorrect.

What submodule that we use was force-pushed into? I don't remember it ever happening.

How comes your submodule config had `file` for wsrep-lib? It never used `file` url, so no bisect could've got you there.

2022-12-21 18:17 UTC, haidong commented
I just updated the PR with what is hopefully better commit message. Hopefully that addresses the confusion. Writing good and clear commit message is difficult, I am open to suggestions.

> How comes your submodule config had file for wsrep-lib? It never used file url, so no bisect could've got you there.

I don't use `file` in submodule config for wsrep-lib. It is a symptom of trying to address the bug I described in the commit message. https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html

2022-12-21 20:27 UTC, vuvova commented
I don't see how [this link](https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html) is relevant. It says
> If you are running a CI system that uses git to check out software for builds, and if that environment uses "git submodule add" to bring in files from the filesystem, then you might be affected by this change.

We do not use _"git submodule add" to bring in files from the filesystem_ so it appears that this change should not apply?

2022-12-21 21:03 UTC, haidong commented
> I don't see how [this link](https://vielmetti.typepad.com/logbook/2022/10/git-security-fixes-lead-to-fatal-transport-file-not-allowed-error-in-ci-systems-cve-2022-39253.html) is relevant.
> We do not use "git submodule add" to bring in files from the filesystem so it appears that this change should not apply?

That article is used to provide background information, not used as the sole justification for this PR.

The symptoms described in that article is exactly the same as the issue caused by `git submodule update` used in MariaDB build, when the build machine's git program has been upgraded to a version that has the CVE-2022-39253 fix. Additionally, that article has a decent summary of CVE-2022-39253.

One of my colleagues who has the same git (version `2.38.1`) had the same issue when building MariaDB 11. @dlenski and @grooverdan  also reported seeing same issue. As more developers and CI systems git program gets updated with the fix for CVE-2022-39253, they too, will have the same problem. I think you should be able to reproduce the same build error if running the build using git `2.38.1` or later.

Even without this problem, I believe this change is warranted (thanks @dlenski !). I described that rationale in the commit message. Pasted below for easy viewing:

```
It not only fixes the problme mentioned above, but also makes the build 
process more robust for the following reasons:

`git submodule update` uses the hash recorded in the superproject and
looks for it in the submodule. Therefore it is important that the local
submodule branch has that commit referenced. This could become
problematic when the submodule's remote has been force-pushed with a new
commit hash, and superproject has the updated hash, but that commit hash
is not available locally in the submodule.

This switch ensures the local submodule tracks its remote branch and its
commits properly. Therefore, it solves the issue caused by inconsistent
commit hash from superproject's record and what's available locally in
submodule.
```

2022-12-21 23:05 UTC, vuvova commented
Okay. I've just upgraded to git 2.38.2, all submodules work, I tried to switch branches back and forth to 10.3 and 10.10 — submodules were updated fine every time.

So, at the moment I don't understand the problem you're trying to fix, I cannot repeat the problem, and I don't see how these symptoms are even possible.

----
As for the second argument, using the remote branch is definitely not a good idea in general. A particular mariadb commit was supposed to work with specific states of submodules, it was designed for them, it was tested with them. Randomly picking any arbitrary later commit is not guaranteed to work. Always building with some random commit from a submodule just because someone someday might possibly violate one of the main git rules and do a force-push into a shared repo (which has never happened before in all the years we've used submodules) — this just makes no sense.

2022-12-21 23:45 UTC, haidong commented
> I've just upgraded to git 2.38.2, all submodules work.

Excellent! I'm glad this has been fixed in `2.38.2`. Developers and CI systems  with version `2.38.1` will still suffer.

> As for the second argument, using the remote branch is definitely not a good idea in general. A particular mariadb commit was supposed to work with specific states of submodules, it was designed for them, it was tested with them. 

That is exactly right. A particular mariadb commit was supposed to work with specific commit of submodules. This change will _not_ change that. It will make it more robust. I'll explain below.

> Randomly picking any arbitrary later commit is not guaranteed to work. Always building with some random commit from a submodule just because someone someday might possibly violate one of the main git rules and do a force-push into a shared repo (which has never happened before in all the years we've used submodules) — this just makes no sense.

This is not the case at all.

Consider this simplified case:
1. MariaDB 11 commit with hash value `1`  uses wsrep-lib commit with hash value `a`;
2. As a result, hash value `a` is stored in the MariaDB 11 commit `1`;
3. Developer clones MariaDB branch 11. S/he will get MariaDB commit `1`, wsrep-lib `a`;
4. wsrep-lib project makes new commit `b` and pushes to github. Here, running `git submodule update --remote` gets the `b` commit locally, but it will NOT randomly change its superproject MariaDB's submodule hash ref `a`;
5. wsrep-lib makes new commit `c`. MariaDB 11 decides to use the `c` commit. This bumps MariaDB 11's hash to `2`, and it has subproject hash `c`;
6. Running `git pull` under MariaDB gets hash `2` subproject hash `c`. The build is going to fail unless you go to the submodule and do a `git pull`, because subproject hash `c` is not available locally. But with this `--remote` switch, that's done automatically.
7. wsrep-lib makes a force push, let's call its commit hash `d`. In this case, commit `c` no longer exist. Upstream MariaDB makes the adjustment so it points to `d`.
8. Developer pulls the latest change from MariaDB 11 with wsrep-lib commit `d`. Once again, that `d` commit won't be available in local wsrep-lib branch using the current method and build will fail. Once again, this switch does the sync automatically.

In summary, this switch will make the build process more robust.

2022-12-22 07:44 UTC, LinuxJedi commented
We have had someone in the MariaDB Foundation affected by this issue in the last week and we struggled to diagnose it. Many thanks for figuring it out.

2022-12-22 07:59 UTC, LinuxJedi requested changes
As can be seen here, and I've reproduced locally, this breaks RocksDB on a fresh checkout of MariaDB Server:

https://buildbot.mariadb.org/#/builders/1/builds/31104/steps/4/logs/stdio

2022-12-22 17:49 UTC, haidong commented
@LinuxJedi  The error is caused by RockDB plugin build. The reason is because the [superproject's ](https://github.com/MariaDB/server/blob/10.3/storage/rocksdb/build_rocksdb.cmake#L189)build_rocksdb.cmake[ file](https://github.com/MariaDB/server/blob/10.3/storage/rocksdb/build_rocksdb.cmake#L189) that calls the submodule (rocksdb) is behind the what the submodule actually contains! That's exactly what `git submodule update --remote` is supposed to expose! So this PR revealed a problem it's supposed to reveal before it has been approved and merged :smile: 

For example, `build_rocksdb.cmake` makes references to `storage/rocksdb/rocksdb/db/compacted_db_impl.cc`. But there is no longer such a file in that location. Had we have this PR fix earlier, we would have known it and fixed it a long time ago.

The `build_rocksdb.cmake` file contains a list of RocksDb source files. I wonder if there is a better way. Figuring that out may be a separate upstream contribution. I'd like to focus on getting the `--remote` switch in now.

2022-12-22 18:42 UTC, haidong commented
I'm still working on this, in case I gave the wrong impression in my last comment.

2022-12-22 19:34 UTC, vuvova commented
@haidong I've tried with 2.38.1 too, no error. What should I do to repeat this behavior?

2022-12-23 05:27 UTC, haidong commented
Hi @vuvova 
> I've tried with 2.38.1 too, no error. What should I do to repeat this behavior?

Strangely, I could no longer reproduce this error!

I tried the following:
- On the same machine that had the issue initially, running the same `cmake` command. It worked fine without reporting the error!
- I then tried running it inside a Ubuntu container. See steps below. Again, I could NOT reproduce the error. If you try the same steps, I'd love to hear your observation:
```
docker run -it --rm --entrypoint="" -v ~/.ssh:/root/.ssh ubuntu bash

# Now I'm inside the container and start building git 2.38.1
apt update
apt install wget make autoconf gcc libz-dev gettext ssh cmake g++ vim libcurl4-openssl-dev libncurses5-dev gnutls-dev bison -y
cd
wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.38.1.tar.gz
tar -zxf git-2.38.1.tar.gz
cd git-2.38.1
./configure --prefix=/usr
make all
make install
git version

# git 2.38.1 successfully built. Clone the MariaDB repo and start building
git clone git@github.com:MariaDB/server.git
cd server
cmake -DPLUGIN_COLUMNSTORE=NO -DPLUGIN_ROCKSDB=NO -DPLUGIN_S3=NO -DPLUGIN_MROONGA=NO -DPLUGIN_CONNECT=NO -DPLUGIN_SPHINX=NO -DPLUGIN_SPIDER=NO -DPLUGIN_TOKUDB=NO -DPLUGIN_PERFSCHEMA=NO -DWITH_WSREP=OFF .
make -j 8

# command below will exit out of the container. The container will then be killed and cleaned away
exit
```
After [more reading of git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules), I noticed that our `.gitmodules` file does NOT specify a specific branch or tag for any submodules we use. In this case `git submodule update --init --remote` is dangerous because it will check out the commit pointed to by remote's default branch's HEAD.

That's the reason behind RocksDB failure pointed out by @LinuxJedi . In this case, the `--remote` switch did cause RocksDB submodule to checkout remote's default branch's latest commit, which caused the failure because it uses C++ 17 standard, among other things.

I now believe the proper way forward is the combination of
- branch/tag included for all submodules used inside `.gitmodules`, preferably tags. Using tags assigned by submodule's upstream maintainer is safe, easy for developers to refer to, and easy to bump up or down for security/regression fixes
and
- adding `--remote` switch to `git submodule --init --recursive`. This ensures MariaDB's submodule uses a commit tagged by submodule's upstream maintainer consistently.
I think we should do this for all future MariaDB releases.

Please feel free to reject this PR. Or if you prefer keeping this PR open until  we finish updating `.gitmodules` so every submodule uses correct branch/tag, I can do that too. In that case, we need to agree which tag to use. For example, the RocksDB submodule uses commit bba5e7bc21093d7cfa765e1280a7c4fdcd284288. Unfortunately that commit is not associated with any tags Facebook assigned. I think we made a mistake of not using a tagged commit.

2022-12-23 08:59 UTC, vuvova commented
Unfortunately, I still don't understand what has the reason for build failures.

As you like, we can keep trying to understand the problem, ideally (but not necessarily) with the way to repeat it. Or if you'd prefer it, I can reject this PR.

2022-12-25 22:41 UTC, haidong commented
@vuvova The RocksDB build failures were caused by submodule rocksdb having the latest commit from its master branch HEAD commit. I fixed it in the latest push.

@LinuxJedi I have tested a rocksdb build successfully locally. I believe it should pass the buildbot CI, but let me know if not.

This change will require us specifying submodule's remote tracking branch in `.gitmodule` file, otherwise it'll track remote's master/main branch. I think that's a good, because a branch name is more readable than a SHA1 hash stored in git object database. It'll also make it easier for us to track submodule project's progress.

2022-12-25 23:26 UTC, vuvova commented
@haidong, I'm afraid you misunderstood. This pull request was created allegedly to fix
```
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'wsrep-lib', but it did not contain f8ff2cfdd4c6424ffd96fc53bcc0f2e1d9ffe137. Direct fetching of that commit failed.
CMake Error at cmake/submodules.cmake:47 (MESSAGE):
  No MariaDB Connector/C! Run
```
build failures. You have to explain what is the reason for this failure and, ideally, how to repeat it.

We cannot accept a fix for a problem we don't understand.

2022-12-28 20:09 UTC, haidong commented
I came across the error again yesterday on my cloud development machine:
```
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'wsrep-lib', but it did not contain f8ff2cfdd4c6424ffd96fc53bcc0f2e1d9ffe137. Direct fetching of that commit failed.
CMake Error at cmake/submodules.cmake:47 (MESSAGE):
  No MariaDB Connector/C! Run
  ```
 The error was produced when I resumed work on a branch from [a different PR](https://github.com/MariaDB/server/pull/2173). I set out to reproduce it again in Ubuntu container using the same branch. Again, I could not reproduce it.

Another thing: please note that the `.gitmodule` submodule spec won't accept tag. It needs to be a real git branch. I tried using a tag in lieu of branch, but git won't accept it.

2023-01-02 23:07 UTC, grooverdan commented
@haidong, note you shouldn't be updating the rocksdb/libmariadb modules in this PR.

So trying to work out what is the state to reproduce this:

```
$ git --version
git version 2.38.1
```

```
$ git reflog
65683807e91 (HEAD -> 10.7, upstream/bb-10.7-monty, upstream/10.7, origin/bb-10.7-monty, origin/10.7) HEAD@{0}: pull: Fast-forward
20928819841 HEAD@{1}: checkout: moving from 404105dade3f75ff6ad146b681acccb0cde047c9 to 10.7

$ git submodule status
 f1e2165c591f074feb47872a8ff712713ec411e1 extra/wolfssl/wolfssl (v5.5.1-stable)
+ade9bb9c3ef5f28a4f076ed3afa455975a8e5ab4 libmariadb (v3.1.15-43-gade9bb9)
+1929e73ecb65b57533669f3e70d7555715c65055 storage/columnstore/columnstore (columnstore-6.3.1-1-2-g1929e73ec)
 3846890513df0653b8919bc45a7600f9b55cab31 storage/maria/libmarias3 (heads/master)
 bba5e7bc21093d7cfa765e1280a7c4fdcd284288 storage/rocksdb/rocksdb (bba5e7b)
+8bfce04189671eb1f06e0fa83dff8c880f31088f wsrep-lib (8bfce04)
```

```
$ b
[0/1] Re-running CMake...
CMake Warning (dev) at CMakeLists.txt:30 (PROJECT):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    CMAKE_PROJECT_VERSION
    CMAKE_PROJECT_VERSION_MAJOR
    CMAKE_PROJECT_VERSION_MINOR
    CMAKE_PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Running cmake version 3.25.1
-- MariaDB 10.7.8
-- Updating submodules
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'libmariadb', but it did not contain 72b40bfaa869f3fe84242471dda989d13983d84c. Direct fetching of that commit failed.
CMake Error at cmake/submodules.cmake:47 (MESSAGE):
  No MariaDB Connector/C! Run

      /usr/bin/git submodule update --init --recursive

  Then restart the build.
Call Stack (most recent call first):
  CMakeLists.txt:152 (INCLUDE)


-- Configuring incomplete, errors occurred!
See also "/home/dan/repos/build-mariadb-server-10.7-base/CMakeFiles/CMakeOutput.log".
See also "/home/dan/repos/build-mariadb-server-10.7-base/CMakeFiles/CMakeError.log".
FAILED: build.ninja 
/usr/bin/cmake --regenerate-during-build -S/home/dan/repos/mariadb-server-10.7-base -B/home/dan/repos/build-mariadb-server-10.7-base
ninja: error: rebuilding 'build.ninja': subcommand failed
```

As expected manual execution failed the same way:
```
~/repos/mariadb-server-10.7-base 10.7
$ git submodule update --init --recursive
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'libmariadb', but it did not contain 72b40bfaa869f3fe84242471dda989d13983d84c. Direct fetching of that commit failed.
```

Looking at submodule:
```
~/repos/mariadb-server-10.7-base/libmariadb tags/v3.2.7~1
$ git show 72b40bfaa869f3fe84242471dda989d13983d84c
fatal: bad object 72b40bfaa869f3fe84242471dda989d13983d84c
```

Looking at the remotes in the submodule:
```
$ git remote show origin
* remote origin
  Fetch URL: https://github.com/MariaDB/mariadb-connector-c.git
  Push  URL: https://github.com/MariaDB/mariadb-connector-c.git
  HEAD branch: 3.3
  Remote branch:
    3.2 tracked
  Local branch configured for 'git pull':
    3.2 merges with remote 3.2
  Local ref configured for 'git push':
    3.2 pushes to 3.2 (local out of date)

$ git config --local -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.worktree=../../../../../../mariadb-server-10.7-base/libmariadb
remote.origin.url=https://github.com/MariaDB/mariadb-connector-c.git
remote.origin.fetch=+refs/heads/3.2:refs/remotes/origin/3.2
branch.3.2.remote=origin
branch.3.2.merge=refs/heads/3.2

$ git branch 
* (HEAD detached at ade9bb9)
  3.2
```

So the current 10.7 libmariadb is on 3.3, but at the time this was checked out the branch was 3.2.

```
~/repos/mariadb-server-10.7-base/libmariadb tags/v3.2.7~1
$ git fetch 

$ git submodule update --init --recursive 
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'libmariadb', but it did not contain 72b40bfaa869f3fe84242471dda989d13983d84c. Direct fetching of that commit failed.
```


So even fetching fails to pull from the 3.3 branch. Adding `branch = 3.3` to the `.gitmodules` as a minimal change isn't sufficient (`git submodule update --init --recursive` doesn't relook at the configuration).

Note, git-clone has a `--remote-submodules` that effectively enables the `--remote` option by default.

So as a reproducible example as I surmise has happened here:
1. repo with branch X was cloned.
1. git submodule init/update created a config `remote.origin.fetch` to the branch of the remote that contained the submodule ref
1. upstream changed the ref of submodule to a ref from a different branch
1. locally git pull changed the submodule ref, but not the `remote.origin.fetch` so its unable to checkout the new reference without --remote. The attempts at finding the ref will fetch the submodule of only the `remote.origin.fetch` branch, which doesn't contain the required submodule branch.

2023-01-03 21:30 UTC, ottok commented
@haidong I am fairly confident you should not use `--remote` - this will just select the latest commit on the submodule and *not honor*  the commit defined in the parent git project as the tracking.

Example showing all repos are at wrong commit:
```
± git submodule update --init --force --remote
Submodule path 'extra/wolfssl/wolfssl': checked out '4f8edb312be8064c16d4c5baebb5d9f129515010'
Submodule path 'libmariadb': checked out 'da9bb98c0cef8097ee50341722f08d5042efbe49'
Submodule path 'storage/columnstore/columnstore': checked out '20535620e0f264c8d7eaf7eb4edf606ce07bd494'
Submodule path 'storage/maria/libmarias3': checked out 'd7028f429bb247c622eb9948d9b8d5356f03cb79'
Submodule path 'storage/rocksdb/rocksdb': checked out 'b965a5a80ee1a70fd5de33818e92b4afa0d9e08c'
Submodule path 'wsrep-lib': checked out 'de3d7b63eab188a54ce5d2f635a610991bf563bc'

± git submodule
+4f8edb312be8064c16d4c5baebb5d9f129515010 extra/wolfssl/wolfssl (heads/master)
+da9bb98c0cef8097ee50341722f08d5042efbe49 libmariadb (heads/3.3)
+20535620e0f264c8d7eaf7eb4edf606ce07bd494 storage/columnstore/columnstore (heads/develop)
+d7028f429bb247c622eb9948d9b8d5356f03cb79 storage/maria/libmarias3 (heads/master)
+b965a5a80ee1a70fd5de33818e92b4afa0d9e08c storage/rocksdb/rocksdb (heads/main)
+de3d7b63eab188a54ce5d2f635a610991bf563bc wsrep-lib (heads/master)
```

In today's 11.0 branch you want to see as the end result:
```
± git submodule
 f1e2165c591f074feb47872a8ff712713ec411e1 extra/wolfssl/wolfssl (v5.4.0-stable-652-gf1e2165c5)
 d9af4fcbc6a7c0ab72b38bb47e0d4fa1f1f83316 libmariadb (v3.3.3)
 5923beeab9397aa22563ff7b1f0f31ad8054bae6 storage/columnstore/columnstore (vcolumnstore-6.4.1-1-35-g5923beeab)
 3846890513df0653b8919bc45a7600f9b55cab31 storage/maria/libmarias3 (libmarias3-3.1.2-36-g3846890)
 bba5e7bc21093d7cfa765e1280a7c4fdcd284288 storage/rocksdb/rocksdb (v5.8-2306-gbba5e7bc2)
 f8ff2cfdd4c6424ffd96fc53bcc0f2e1d9ffe137 wsrep-lib (heads/master-6-gf8ff2
 ```

2023-01-03 21:43 UTC, ottok commented
The error message is quite clear:
```
$ git submodule update --init --depth 300
remote: Enumerating objects: 7881, done.
remote: Counting objects: 100% (6653/6653), done.
remote: Compressing objects: 100% (2036/2036), done.
remote: Total 5442 (delta 4468), reused 4272 (delta 3404), pack-reused 0
Receiving objects: 100% (5442/5442), 1.26 MiB | 6.84 MiB/s, done.
Resolving deltas: 100% (4468/4468), completed with 569 local objects.
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
From https://github.com/mariadb-corporation/mariadb-columnstore-engine
 * [new tag]           columnstore-1.4.3-6 -> columnstore-1.4.3-6
 * [new tag]           columnstore-1.5.2-1 -> columnstore-1.5.2-1
 * [new tag]           columnstore-1.5.3-1 -> columnstore-1.5.3-1
fatal: transport 'file' not allowed
fatal: Fetched in submodule path 'storage/columnstore/columnstore', but it did not contain 5923beeab9397aa22563ff7b1f0f31ad8054bae6. Direct fetching of that commit failed.

$ cd storage/columnstore/columnstore

[storage/columnstore/columnstore] develop $ git show 5923beeab9397aa22563ff7b1f0f31ad8054bae6.
fatal: ambiguous argument '5923beeab9397aa22563ff7b1f0f31ad8054bae6.': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

The commit https://github.com/mariadb-corporation/mariadb-columnstore-engine/commit/5923beeab9397aa22563ff7b1f0f31ad8054bae6 is not found in the last 300 commits of the ColumnStore default branch 'develop' because it does not exist there.

There are two possible solutions:
1. Stop using `--depth 1` to and do full checkout ensure the full submodule is cloned and commit is found.
2. Define the desired branch in `.gitmodules` for each submodule and manage the clone depths manually.

I took a quick stab at 2 but didn't get it working.

Doing a full clone isn't that bad either:

```
± du -shc .git/modules/*
488M	.git/modules/extra
8.9M	.git/modules/libmariadb
365M	.git/modules/storage
1.6M	.git/modules/wsrep-lib
863M	total
```

## Summary

If you run in to this error, use this workaround:

```
rm -rf extra/wolfssl/wolfssl libmariadb storage/columnstore/columnstore storage/maria/libmarias3 storage/rocksdb/rocksdb wsrep-lib
rm -rf .git/modules/*

git submodule update --init
```

2023-01-03 22:23 UTC, haidong commented
I agree with @ottk's suggestion above. I had hoped that the combination of `--remote` switch and explicit definition of `branch` in `.gitmodule` would provide a better solution. But `branch` can change, which wouldn't make sense. I think it would have been a better solution had `tag` is allowed in `.gitmodule`.

Thanks all for the input!

2023-01-03 22:23 UTC, closed without merging

2023-01-04 00:02 UTC, vuvova commented
Thanks, @ottok, for helping to resolve this!

---
Unfortunately, it looks like the reason for this error will remain a mystery. @grooverdan no luck with how-to-repeat?

2023-01-04 07:42 UTC, ottok commented
@grooverdan You can repeat this by running:
```
$ git --version
git version 2.38.1

$ rm -rf extra/wolfssl/wolfssl libmariadb storage/columnstore/columnstore storage/maria/libmarias3 storage/rocksdb/rocksdb wsrep-lib
$ rm -rf .git/modules/*
$ git submodule update --init --depth 1
```

Deleting the git repository and then cloning the submodules with `--depth 1` will ensure that git will not find all commits and thus spit out the error message displayed in this PR discussion.

2023-01-04 08:52 UTC, vuvova commented
@ottok, that didn't work for me. I start with a completely new repo:
```
$ git checkout mariadb-10.2.35
Updating files: 100% (21400/21400), done.
Note: switching to 'mariadb-10.2.35'.
...
HEAD is now at 6d3792a9a2e List of unstable tests for 10.2.35 release
$ rm -rf extra/wolfssl/wolfssl libmariadb storage/columnstore/columnstore storage/maria/libmarias3 storage/rocksdb/rocksdb wsrep-lib .git/modules/*
$ git submodule update --init --depth 1
Submodule 'libmariadb' (https://github.com/MariaDB/mariadb-connector-c) registered for path 'libmariadb'
Submodule 'storage/rocksdb/rocksdb' (https://github.com/facebook/rocksdb.git) registered for path 'storage/rocksdb/rocksdb'
Cloning into '.../libmariadb'...
Cloning into '.../storage/rocksdb/rocksdb'...
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Enumerating objects: 257, done.
remote: Counting objects: 100% (257/257), done.
remote: Compressing objects: 100% (149/149), done.
remote: Total 151 (delta 93), reused 20 (delta 1), pack-reused 0
Receiving objects: 100% (151/151), 221.96 KiB | 4.19 MiB/s, done.
Resolving deltas: 100% (93/93), completed with 90 local objects.
From https://github.com/MariaDB/mariadb-connector-c
 * branch            62427520a5ba20e42fe51f5045062a7a9cadb466 -> FETCH_HEAD
Submodule path 'libmariadb': checked out '62427520a5ba20e42fe51f5045062a7a9cadb466'
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
remote: Enumerating objects: 2244, done.
remote: Counting objects: 100% (2244/2244), done.
remote: Compressing objects: 100% (1198/1198), done.
remote: Total 1256 (delta 920), reused 169 (delta 24), pack-reused 0
Receiving objects: 100% (1256/1256), 1.28 MiB | 4.95 MiB/s, done.
Resolving deltas: 100% (920/920), completed with 875 local objects.
From https://github.com/facebook/rocksdb
 * branch            bba5e7bc21093d7cfa765e1280a7c4fdcd284288 -> FETCH_HEAD
Submodule path 'storage/rocksdb/rocksdb': checked out 'bba5e7bc21093d7cfa765e1280a7c4fdcd284288'
$ git checkout bb-10.3-serg
Updating files: 100% (11195/11195), done.
Previous HEAD position was 6d3792a9a2e List of unstable tests for 10.2.35 release
branch 'bb-10.3-serg' set up to track 'origin/bb-10.3-serg'.
Switched to a new branch 'bb-10.3-serg'
$ git submodule update 
From https://github.com/MariaDB/mariadb-connector-c
 * [new tag]         v3.1.11    -> v3.1.11
remote: Enumerating objects: 10923, done.
remote: Counting objects: 100% (10853/10853), done.
remote: Compressing objects: 100% (2928/2928), done.
remote: Total 10534 (delta 7870), reused 10211 (delta 7561), pack-reused 0
Receiving objects: 100% (10534/10534), 4.81 MiB | 5.83 MiB/s, done.
Resolving deltas: 100% (7870/7870), completed with 201 local objects.
From https://github.com/MariaDB/mariadb-connector-c
 * branch            7fdb3eab66384a355475704332d11cc1ab82499a -> FETCH_HEAD
Submodule path 'libmariadb': checked out '7fdb3eab66384a355475704332d11cc1ab82499a'
```
As you can see, `git submodule update` downloads more commits as needed, I don't get an error as in the bug description.

2023-01-04 18:25 UTC, ottok commented
@vuvova What is your git version?

2023-01-04 18:39 UTC, vuvova commented
Sorry. I was going to add it to the output above, but forgot
```
$ git version
git version 2.38.2
```

2023-01-04 19:40 UTC, haidong commented
I can confirm @vuvova 's [observation above](https://github.com/MariaDB/server/pull/2388#issuecomment-1370634491) using git `2.38.1`. My experiment was conducted in a clean slate using the Ubuntu container described in a [previous comment](https://github.com/MariaDB/server/pull/2388#issuecomment-1363631446).

I suggest let's keep this in the back of our head and revisit if it causes issues in CI or production build environment.

2023-06-26 09:35 UTC, vuvova commented
This turned out to be `git` bug: https://lore.kernel.org/git/ZJR5SPDj4Wt_gmRO@pweza/
To quote from there:

> In submodule--helper.c, fetch_in_submodule() function, there're lines:
>
```c
         if (oid) {
                 char *hex = oid_to_hex(oid);
                 char *remote = get_default_remote();

                 strvec_pushl(&cp.args, remote, hex, NULL);
                 free(remote);
         }
```
> 
> this `get_default_remote()` appears to be getting the default remote name for the main repository and then uses it to fetch from the submodule.
> 
> It happens that my default remote isn't "origin" (long story), it's "github", but in the submodule it's of course "origin", there's no
> "github" remote there. As a result, `git submodule update` runs the command
> 
>  ```git fetch github ${commit_hash}```
> 
> in the submodule, and that's interpreted as 'file' transport.
> 
> To repeat this you need a repository where the default remote isn't "origin" and a submodule where the commit cannot be fetched by simply `git fetch` and needs a direct fetch.

as a workaround, fetch and checkout inside the submodule manually. Or, as we do in buildbot,
```
git submodule foreach --recursive 'git fetch origin $sha1;git checkout --force FETCH_HEAD'
```

2023-06-27 16:45 UTC, haidong commented
That makes sense @vuvova. Now that you pointed out what appear to be a bug, hope it'll be fixed. It will be useful to update this PR when/if you notice this is addressed.

2023-06-28 23:26 UTC, dlenski commented
> This turned out to be git bug: https://lore.kernel.org/git/ZJR5SPDj4Wt_gmRO@pweza/

Wow, yes, that is a great catch.

I know that some of the confusion around submodule updates was also exacerbated by using the `ignore=all` flag in `.gitmodules`, which causes local changes to submodules to be mostly-invisible to `git {log,show,diff}`; thankfully, @vuvova already addressed that in https://github.com/MariaDB/server/commit/3c6f108540862ef91889ee2bf975fad64237dabb :pray: