Backport GitLab CI to 10.5
MariaDB/server pull request #2476
Opened 2023-02-02 20:03 UTC by robinnewhouse

## Description
Add .gitlab-ci.yml file to earliest supported branch to enable
automated building and testing for all MariaDB major branches.

Note to mergers:
GitLab CI is available for branches >= 10.6. This commit includes a
GitLab CI file identical to that in branches >= 10.6, except for the
MARIADB_MAJOR_VERSION variable which should reflect the branch version.
A modified CI will be included in branches 10.4 with PR !2418.
Also changed is the `allow_failure: true` for the MSAN build,
which should be merged up to later branches.

## How can this PR be tested?
The pipeline for these changes successfully completes and a [public pipeline](https://salsa.debian.org/robinnewhouse/mariadb-server-mirror/-/commits/10.5-backport-CI) is available.

## Basing the PR against the correct MariaDB version
- [x] *This is a CI feature and the PR is based against the oldest branch with Gitlab-CI*

## Copyright
All new code of the whole pull request, including one or several files
that are either new files or modified ones, are contributed under the
BSD-new license. I am contributing on behalf of my employer
Amazon Web Services, Inc.

2023-02-02 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2476) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2476) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2476) it.</sub>

2023-02-13 16:46 UTC, robinnewhouse commented
@LinuxJedi while we’re on the subject of CI, would you mind taking a look at this as well?

2023-02-14 15:39 UTC, LinuxJedi requested changes
Is this different to the 10.4 one?

If it is identical then this won't be needed as it will be merged up through 10.5 soon. If it is different it is better to wait until the 10.4 one is merged up and then have this PR as a diff between that and this one.

2023-02-14 16:10 UTC, robinnewhouse commented
This should actually be identical to the 10.6+ branches. 10.4 is the only one now with special SSL treatment (i.e. requires bundled).

This PR is intended to backport the 10.6+ CI so that all active branches are covered.

2023-02-15 08:08 UTC, LinuxJedi commented
> This should actually be identical to the 10.6+ branches. 10.4 is the only one now with special SSL treatment (i.e. requires bundled).
> 
> This PR is intended to backport the 10.6+ CI so that all active branches are covered.

OK, best to wait for the 10.4 to merge up. Then this PR can be a diff. This will avoid conflicts as much as possible for whoever does the merging.

2023-03-17 20:00 UTC, ottok commented
@LinuxJedi This was now refreshed, and merge 10.4->10.5 happened long time ago. Can you please merge this now?

2023-04-09 21:57 UTC, ottok commented
The PR #2560 should be reviewed and merged with higher priority than this one.

2023-05-19 15:25 UTC, merged