MDEV-24931: Assertion `prefix_size <= width' failed in Bitmap<width>::is_prefix(uint) & UBSAN: shift exponent 32 is too large for 32-bit type 'int' in generate_derived_keys_for_table
MariaDB/server pull request #2520
Opened 2023-03-03 12:41 UTC by Weijun-H

- [x] *The Jira issue number for this PR is: MDEV-24931*

## Description

## How can this PR be tested?
The test is append to `join.test`

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

2023-03-03 12:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2520) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2520) before we can accept your contribution.<br/>**7** out of **12** committers have signed the CLA.<br/><br/>:white_check_mark: spetrunia<br/>:white_check_mark: Weijun-H<br/>:white_check_mark: grooverdan<br/>:white_check_mark: an3l<br/>:white_check_mark: ffontaine<br/>:white_check_mark: LinuxJedi<br/>:white_check_mark: haidong<br/>:x: Thirunarayanan<br/>:x: robinnewhouse<br/>:x: igorbabaev<br/>:x: vuvova<br/>:x: montywi<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2520) it.</sub>

2024-02-22 23:59 UTC, keeper commented
Hi @Weijun-H , could you elaborate more on why does it make more sense using `DBUG_ASSERT(idx <= ARRAY_ELEMENTS);`  to check the boundary of the prefix in your commit log?

Also in your commit log stated that this commit also fix a potential UB but I believe the issue still exists in https://github.com/MariaDB/server/blob/70be59913c90e93fe5136d6f6df03c4254aa515d/sql/sql_select.cc#L13035, could you also verify that?

2024-03-21 05:26 UTC, grooverdan requested changes
Good test case. Though including the other test case from the MDEV would be good.

Per @vaintroub's MDEV comment, the fix shouldn't be in the is_prefix, its why is_prefix is called with the greater value. `generate_derived_keys_for_table` is the most likely case for improvement.

Note sure if `typedef ulong key_part_map`; should be raised to ulonglong as well.

Same MDEV: #3139

2025-04-15 18:54 UTC, svoj commented
Closing as there was no response to requested changes. Feel free to reopen if you're aiming to continue work on it.

2025-04-15 18:54 UTC, closed without merging