MDEV-30351 crash in Item_func_left::val_str
MariaDB/server pull request #2542
Opened 2023-03-11 10:08 UTC by Weijun-H

- [x] *The Jira issue number for this PR is: MDEV-30351

## Description
crash in `Item_func_left::val_str`
## How can this PR be tested?
The test is appended to `func_str`

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.

2023-03-11 12:05 UTC, Weijun-H commented
I checked the failed tests, and they seem not to relate to my modification.

2023-03-29 04:43 UTC, grooverdan requested changes
First mistake:

```
/home/dan/repos/mariadb-server-10.3/sql/item_strfunc.cc:1650:8: error: variable 'char_pos' is used uninitialized whenever '&&' condition is false [-Werror,-Wsometimes-uninitialized]
      (res->charset() != NULL && (res->length() <= (char_pos= res->charpos((int) length)))))
       ^~~~~~~~~~~~~~~~~~~~~~
/home/dan/repos/mariadb-server-10.3/sql/item_strfunc.cc:1653:26: note: uninitialized use occurs here
  tmp_value.set(*res, 0, char_pos);
                         ^~~~~~~~
/home/dan/repos/mariadb-server-10.3/sql/item_strfunc.cc:1650:8: note: remove the '&&' if its condition is always true
      (res->charset() != NULL && (res->length() <= (char_pos= res->charpos((int) length)))))
       ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/dan/repos/mariadb-server-10.3/sql/item_strfunc.cc:1641:16: note: initialize the variable 'char_pos' to silence this warning
  uint char_pos;
               ^
                = 0
1 error generated.
```

Even after initializing char_pos to 0, while this prevents a crash, it doesn't generate the right result. Tracing this through it returns a empty string. It should return 10 characters of the timestamp (as examined in gdb around the changed code).

I got a solution of the following:
```
diff --git a/sql/item_strfunc.cc b/sql/item_strfunc.cc
index 90bc784ed01..5be5b8da82a 100644
--- a/sql/item_strfunc.cc
+++ b/sql/item_strfunc.cc
@@ -1646,8 +1646,10 @@ String *Item_func_left::val_str(String *str)
   /* if "unsigned_flag" is set, we have a *huge* positive number. */
   if ((length <= 0) && (!args[1]->unsigned_flag))
     return make_empty_result();
-  if ((res->length() <= (ulonglong) length) ||
-      (res->charset() != NULL && (res->length() <= (char_pos= res->charpos((int) length)))))
+  if (res->charset() == NULL)
+    char_pos= length;
+  else if ((res->length() <= (ulonglong) length) ||
+      (res->length() <= (char_pos= res->charpos((int) length))))
     return res;
 
   tmp_value.set(*res, 0, char_pos);
```

Can you construct a test case that effectively tests the result?

Can you put a [commit message](https://mariadb.com/kb/en/contributing-code/#what-to-have-in-a-commit-comment) that describes the problem/solution more fully.

Can you rebase on 10.4 (we might cherry pick to 10.3 later)?

2023-03-29 09:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2542) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2542) before we can accept your contribution.<br/>**7** out of **22** committers have signed the CLA.<br/><br/>:white_check_mark: an3l<br/>:white_check_mark: LinuxJedi<br/>:white_check_mark: is-this-echo<br/>:white_check_mark: kevincheng2<br/>:white_check_mark: cvicentiu<br/>:white_check_mark: grooverdan<br/>:white_check_mark: Weijun-H<br/>:x: montywi<br/>:x: vuvova<br/>:x: Thirunarayanan<br/>:x: lornacluo<br/>:x: HugoWenTD<br/>:x: igorbabaev<br/>:x: abarkov<br/>:x: dr-m<br/>:x: sysprg<br/>:x: sanja-byelkin<br/>:x: andrelkin<br/>:x: mariadb-YuchenPei<br/>:x: vlad-lesin<br/>:x: christian7007<br/>:x: midenok<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2542) it.</sub>

2023-03-30 01:09 UTC, grooverdan commented
Simpler test: `SELECT UNHEX('0032') in (LEFT(UNHEX('003200'), 2),'dog');` returning 1 - crashes previous.

Getting a second review from @abarkov so wait off on test changes.

2023-03-30 04:13 UTC, abarkov requested changes
It is not expected that `String::charset()` returns NULL.
The problem should be fixed in other place, where this String instance is initialized.

From a glance, `str->set_charset(&my_charset_bin)` should be added to `Item_func_unhex::val_str()`.

2023-03-30 05:15 UTC, grooverdan commented
> However, even if we fix `in_string`, the call for `str->set_charset(&my_charset_bin)` should still be added to `Item_func_unhex::val_str()`, because `str->m_charset` can be set to any arbitrary value when `str` is passed to `Item_func_unhex::val_str()`

I assume the same applies to `Item_func_weight_string::val_str` that was the original trigger in the MDEV too.

2023-03-30 06:28 UTC, abarkov commented
Correct. Any val_str() must set str->m_charset according to Item::collation.collation.

2023-03-31 03:27 UTC, grooverdan commented
Thanks @Weijun-H ,I just did some minor adjustments on test cases to show for WEIGHT_STRING that its returning the right value and listed the functions (and reviewers) in the commit message.

Thanks for making the change to fix this bug. I'll merge this once the CI passes the required tests.

2023-03-31 03:53 UTC, merged