MDEV-31022 SIGSEGV in maria_create from create_internal_tmp_table
MariaDB/server pull request #2596
Opened 2023-04-13 02:54 UTC by rex-johnston

Pull request created in: https://jira.mariadb.org/browse/MDEV-31022

2023-04-16 13:43 UTC, spetrunia commented on sql/sql_select.cc
> +
This doesn't seem to make any sense.  key_length is some length in bytes, isn't it?

I am trying this example:

```
create table t11 (
  a int, 
  b blob
);
insert into t11
select seq, seq from seq_1_to_100;

select distinct a,b from t11;
```

I get a breakpoint on this line and I see `keyinfo->key_length=4` . 

The code below will allocate 4 MARIA_KEYDEF structures:

```
    keydef= (MARIA_KEYDEF*) alloc_root(&table->mem_root, sizeof(*keydef) * len);
```

It is not clear why.

2023-04-16 13:47 UTC, spetrunia requested changes
... another thing that's not clear to me is why we need multiple MARIA_KEYDEF structures at all.  Could you please clarify? 

I see Roel has posted a comment saying the bug repeats only after some Monty's commit. Did Monty's commit indeed introduce a bug (and what it was?)  or we were just lucky before?

2023-04-16 22:31 UTC, rex-johnston commented
> ... another thing that's not clear to me is why we need multiple MARIA_KEYDEF structures at all. Could you please clarify?

`create_internal_tmp_table()` near the end calls `maria_create(...  uint keys,MARIA_KEYDEF *keydefs, ... )`
with the shown parameters used like this

```
  for (i=0, keydef=keydefs ; i < keys ; i++ , keydef++)
  {
...
  }
```

indicating it expects an array of key def structures and it is the calling of this routine with keys > 1 that causes all sorts of issues if keydefs is singular and allocated on the stack.

I clearly have misunderstood the meaning of `keyinfo->key_length`.  Fixing now.

2023-04-17 09:26 UTC, spetrunia commented
Good.

Also, I don't understand the intent of this logic:
```
keyinfo->key_length>1?keyinfo->key_length:1;
```

Does it mean that `keyinfo->key_length` may be `0` in some cases?   (It can't be negative because it's an "uint").

2023-04-17 19:50 UTC, rex-johnston commented
I was overthinking it.  Going into create_internal_tmp_table(),  table->s->keys contains the number of MARIA_KEYDEF structures required later on in maria_create().

using the provided test case.

```
CREATE TABLE t (c CHAR(1) NULL);
INSERT INTO t (c) VALUES (1);
SET sql_mode='',optimizer_where_cost=1,big_tables=1,in_predicate_conversion_threshold=2;
SELECT * FROM t WHERE c IN ('','');
```

and running the server under rr, thus


```
(gdb) break maria_create
Breakpoint 1 at 0x55be3263ea8d: file /home/rex/src/mariadb/server.31022/storage/maria/ma_create.c, line 66.
(gdb) cont
Continuing.
2023-04-18  6:38:04 0 [Warning] Could not increase number of max_open_files to more than 1024 (request: 321940)
2023-04-18  6:38:04 0 [Warning] Changed limits: max_open_files: 1024  max_connections: 151 (was 151)  table_cache: 421 (was 2000)
[New Thread 2594.2622]
[New Thread 2594.2595]
[New Thread 2594.2596]
[New Thread 2594.2597]
[New Thread 2594.2598]
[New Thread 2594.2599]
[New Thread 2594.2600]
[New Thread 2594.2601]
[New Thread 2594.2602]
[New Thread 2594.2603]
[Switching to Thread 2594.2622]

Thread 2 hit Breakpoint 1, maria_create (name=0x7f4aec083728 "/tmp/#sql-temptable-a22-3-3", datafile_type=STATIC_RECORD, keys=2, keydefs=0x7f4aec088850, columns=2, 
    columndef=0x7f4aec083558, uniques=0, uniquedefs=0x7f4b3805ccc0, ci=0x7f4b3805cc60, flags=260) at /home/rex/src/mariadb/server.31022/storage/maria/ma_create.c:66
66	  int errpos,save_errno, create_mode= O_RDWR | O_TRUNC, res;
(gdb) p keys
$1 = 2
(gdb) up
#1  0x000055be321030d1 in create_internal_tmp_table (table=0x7f4aec082a10, keyinfo=0x7f4aec083960, start_recinfo=0x7f4aec083558, recinfo=0x7f4aec02cf10, 
    options=2164529920) at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:21954
21954	    if (unlikely((error= maria_create(share->path.str, file_type, share->keys,
(gdb) watch -l share->keys
Hardware watchpoint 2: -location share->keys
(gdb) reverse-cont
Continuing.

Thread 2 hit Hardware watchpoint 2: -location share->keys

Old value = 2
New value = 1
0x000055be321e918c in TABLE::add_tmp_key (this=0x7f4aec082a10, key=1, key_parts=1, next_field_no=0x55be320ed6df <get_next_field_for_derived_key(uchar*)>, 
    arg=0x7f4b3805cdf0 "", unique=false) at /home/rex/src/mariadb/server.31022/sql/table.cc:8467
8467	  s->keys++;
(gdb) where
#0  0x000055be321e918c in TABLE::add_tmp_key (this=0x7f4aec082a10, key=1, key_parts=1, next_field_no=0x55be320ed6df <get_next_field_for_derived_key(uchar*)>, 
    arg=0x7f4b3805cdf0 "", unique=false) at /home/rex/src/mariadb/server.31022/sql/table.cc:8467
#1  0x000055be320ed99b in generate_derived_keys_for_table (keyuse=0x7f4aec07f9a0, count=1, keys=1) at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:14028
#2  0x000055be320eddd0 in generate_derived_keys (keyuse_array=0x7f4aec02b028) at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:14114
#3  0x000055be320db935 in sort_and_filter_keyuse (join=0x7f4aec02acc0, keyuse=0x7f4aec02b028, skip_unprefixed_keyparts=true)
    at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:7448
#4  0x000055be320d5a50 in make_join_statistics (join=0x7f4aec02acc0, tables_list=..., keyuse_array=0x7f4aec02b028)
    at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:5582
#5  0x000055be320cafde in JOIN::optimize_inner (this=0x7f4aec02acc0) at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:2572
#6  0x000055be320c8833 in JOIN::optimize (this=0x7f4aec02acc0) at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:1900
#7  0x000055be320d45c0 in mysql_select (thd=0x7f4aec0022f8, tables=0x7f4aec029800, fields=..., conds=0x7f4aec02a1a0, og_num=0, order=0x0, group=0x0, having=0x0, 
    proc_param=0x0, select_options=2164525824, result=0x7f4aec02ac98, unit=0x7f4aec006740, select_lex=0x7f4aec0291e8)
    at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:5139
#8  0x000055be320c31d5 in handle_select (thd=0x7f4aec0022f8, lex=0x7f4aec006668, result=0x7f4aec02ac98, setup_tables_done_option=0)
    at /home/rex/src/mariadb/server.31022/sql/sql_select.cc:611
#9  0x000055be3206af22 in execute_sqlcom_select (thd=0x7f4aec0022f8, all_tables=0x7f4aec029800) at /home/rex/src/mariadb/server.31022/sql/sql_parse.cc:6267
#10 0x000055be320621ac in mysql_execute_command (thd=0x7f4aec0022f8, is_called_from_prepared_stmt=false) at /home/rex/src/mariadb/server.31022/sql/sql_parse.cc:3949
#11 0x000055be3206fafa in mysql_parse (thd=0x7f4aec0022f8, rawbuf=0x7f4aec029140 "SELECT * FROM t WHERE c IN ('','')", length=34, parser_state=0x7f4b3805e120)
    at /home/rex/src/mariadb/server.31022/sql/sql_parse.cc:7999
#12 0x000055be3205c027 in dispatch_command (command=COM_QUERY, thd=0x7f4aec0022f8, packet=0x7f4aec020fe9 "SELECT * FROM t WHERE c IN ('','')", packet_length=34, 
    blocking=true) at /home/rex/src/mariadb/server.31022/sql/sql_parse.cc:1894
#13 0x000055be3205a9eb in do_command (thd=0x7f4aec0022f8, blocking=true) at /home/rex/src/mariadb/server.31022/sql/sql_parse.cc:1407
#14 0x000055be3223cbca in do_handle_one_connection (connect=0x55be36a73f38, put_in_cache=true) at /home/rex/src/mariadb/server.31022/sql/sql_connect.cc:1416
#15 0x000055be3223c944 in handle_one_connection (arg=0x55be36a73f38) at /home/rex/src/mariadb/server.31022/sql/sql_connect.cc:1318
#16 0x000055be3273bb04 in pfs_spawn_thread (arg=0x55be369a1048) at /home/rex/src/mariadb/server.31022/storage/perfschema/pfs.cc:2201
#17 0x00007f4b3b7c8fd4 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#18 0x00007f4b3b8488d0 in clone () from /lib/x86_64-linux-gnu/libc.so.6

```

illustrates where table->s->keys is incremented past 1.

2023-04-20 21:35 UTC, rex-johnston commented
... and in answer to why commit bd9ca2a0e3dfb00da226822cea53bb856e8393f0 caused this issue

drop_unused_derived_keys() was altered to allow /* remove all keys except the chosen one and unique keys */
so in this case 

```
(gdb) p tmp_tbl->s->key_info->name
$10 = {str = 0x55be32f30e59 "distinct_key", length = 12}
(gdb) p (tmp_tbl->s->key_info+1)->name
$11 = {str = 0x7f4aec083b28 "key1", length = 4}
```

`tmp_tbl->use_index(tab->ref.key, &tab->keys);` is called with `tab->keys == 2`

2023-04-25 19:55 UTC, spetrunia commented
Debugging the testcase...

Ok, so after Monty's patch, TABLE::use_index() may decide to keep two indexes. (One index is to be used for ref access, the other index is a unique index to remove duplicates). This is fine.

Eventually we arrive at create_internal_tmp_table() which calls maria_create().

create_internal_tmp_table() allocates and bzero'es two MARIA_KEYDEF structures. 
But it does fill only the first one! The second one is always all-zeros (or I miss something).

For the testcase of this bug with the patch applied:
```
  #0  maria_create (name=0x7fff5898b0b8 "/tmp/#sql-temptable-3519-4-1", datafile_type=STATIC_RECORD, keys=2, keydefs=0x7fff589900b0, columns=2, columndef=0x7fff5898aee8,    uniques=0, uniquedefs=0x7ffff00f3eb0, ci=0x7ffff00f3ef0, flags=260) at /home/psergey/dev-git2/11.0-review/storage/maria/ma_create.c:73
  (More stack frames follow...)
```
keys=2, ok.
```
(gdb) p keydefs[0].keysegs
  $40 = 1                       
(gdb) p keydefs[0].seg
  $41 = (HA_KEYSEG *) 0x7fff5898b4c8
```
OK.
```
(gdb) p keydefs[1].keysegs
  $43 = 0
(gdb) p keydefs[1].seg
  $44 = (HA_KEYSEG *) 0x0
```

An index with 0 keyparts and no keypart definitions? Is this really ok?

2023-04-26 18:47 UTC, spetrunia commented
It's interesting that test coverage didn't catch anything (or did  it? @rex-johnston  did you check buildbot?) 

I've tried to make `create_internal_tmp_table`  to really handle the case with multiple indexes.
The result is here:
 https://github.com/MariaDB/server/tree/bb-11.0-MDEV-31022-variant2

(the only tricky thing I saw was: there is code which sets `share->uniques=1;` before the execution reaches `create_internal_tmp_table`...  So  the code in `create_internal_tmp_table` has to assume the table may have at most one unique constraint.  Currently, it is so. )

2025-02-27 15:42 UTC, closed without merging