MDEV-30619: Parallel Slave SQL Thread Can Update Seconds_Behind_Master with Active Workers
MariaDB/server pull request #2682
Opened 2023-06-29 15:55 UTC by bnestere

If the workers of a parallel replica are busy (potentially with long
queues), but the SQL thread has no events left to distribute (so it
goes idle), then the next event that comes from the primary will
update mi->last_master_timestamp with its timestamp, even if the
workers have not yet finished.

This patch changes the parallel replica logic which updates
last_master_timestamp after idling from using sql_thread_caught_up
(added in MDEV-29639) to using rli queued/dequeued event counters.
That is, if the queued count is equal to the dequeued count, it
means all events have been processed and the replica is idle.

Notes:
 * MDEV-29639 changed when sql_thread_caught_up was updated so it
could be used to set last_master_timestamp. This patch additionally
reverts those changes.
 * Renamed rpl_delayed_parallel_slave_sbm.test to
rpl_parallel_sbm.test to be more general to cover this test case as
well.

The first commit on the branch renames a test to serve a more general
case so it can be extended for the purpose of this patch. The second
commit on the branch is the regression to show the issue. The last
commit on the branch is the patch to fix the issue.

2023-06-30 07:43 UTC, knielsen reviewed
I think to push this to a stable release as a bugfix, there needs to be a clear description of how Seconds_Behind_Master precisely should work, from the point of view of the user. If that is not clear, then it's not possible to know if a bugfix actually makes the behaviour correct. And the current documentation in the knowledgebase seems insufficient:

  "Difference between the timestamp logged on the master for the event that the replica is currently processing, and the current timestamp on the replica. Zero if the replica is not currently processing an event. With [parallel replication](https://mariadb.com/kb/en/parallel-replication/), seconds_behind_master is updated only after transactions commit."

The Seconds_Behind_Master I think has been modified a number of times and the actual semantics seems quite complex. Here is some old discussions:

    https://lists.launchpad.net/maria-developers/msg08958.html
    https://lists.launchpad.net/maria-developers/msg08961.html

I *think* the behaviour has changed somewhat since then due to various user requests etc., but I wonder if anyone actually understands exactly how it's supposed to work in detail.
So I think it's necessary to create a precise description of the behaviour of Seconds_behind_master, to show that the expected behaviour is actually known and can be matched to the code, and which could be put in the documentation when this is released.

2023-06-30 16:55 UTC, bnestere commented
Hi @knielsen!

Thanks for the feedback; that is a good point, the documentation is indeed lagging behind. As a starting point in its extension, I propose something like:
 
"Difference between the timestamp logged on the master for the event that the replica is currently processing, and the current timestamp on the replica. Zero if the replica is not currently processing an event. With serial replication, Seconds_Behind_Master is updated when the SQL thread reads a transaction from the relay log for execution. With parallel replication, Seconds_Behind_Master is updated only after transactions commit. Starting in 10.3.38, 10.4.28, 10.5.19, 10.6.12, 10.8.7, 10.9.5, 10.10.3, and 10.11.2, an exception is drawn on the parallel replica to additionally update Seconds_Behind_Master when the first transaction after idling is read from the relay log, to provide a more reliable lag estimate for the duration until the transaction commits."

Where MDEV-29639 is the basis for the extension, as it added a check when an event is read from the relay log to update `SBM` dependent on the idleness of the SQL thread. Then note that MDEV-30619 was opened alongside MDEV-29639's closure because the solution was incomplete, with the intention to extend the check to also check the state of the worker threads. However, after working on MDEV-30619, the former's approach being dependent on the idleness of the SQL thread now seems wrong entirely to me (rather than just incomplete), and this changes the "idleness check" to just use the progress of the worker threads. I tried to capture both changes in the documentation proposition above :)

2023-07-02 19:53 UTC, knielsen commented
Thanks, @bnestere , looks pretty good to me. It's good that this can be described in a single paragraph, even if the rules for SBM are somewhat complex.
(There's another can of worms with exactly what the "timestamp logged on the master" becomes set to, if it's still like it used to be. But that's not really related to this patch, I think it's fine like this for now.)

2023-07-17 16:20 UTC, andrelkin commented on sql/rpl_parallel.cc
> -  struct rpl_parallel_entry *e;
What do you think to keep this block in `#ifndef DBUG_OFF` and assert its `return` is equal the main branch's one?

2023-07-17 16:52 UTC, andrelkin commented on sql/rpl_parallel.cc
> +  return rli->last_inuse_relaylog->queued_count ==
For safety let's install an assert claiming equality for the two at slave start time, e.g into [rpl_parallel::reset()](https://github.com/MariaDB/server/blob/bb-10.4-MDEV-30619/sql/rpl_parallel.cc#L2275).

2023-07-18 10:02 UTC, andrelkin requested changes

2023-07-18 10:02 UTC, andrelkin commented on sql/slave.cc
> +    if ((unlikely(rli->last_master_timestamp == 0) ||
As it pointed earlier `rli->last_master_timestamp == 0` must fall under `rli->last_master_timestamp < ev->when`, *and* (now it got clear to me) at that point `queued_count == dequeued_count` we could remove l.4182 disjunction argument or convert into `assert(lmt != 0 | queued == dequeued)`. For safely I suggest to do so in 11.3.

2023-07-24 16:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2682) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2682) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: bnestere<br/>:x: andrelkin<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2682) it.</sub>

2023-07-25 14:19 UTC, merged