MDEV-14448: Ctrl-C should not exit the client
MariaDB/server pull request #2815
Opened 2023-11-02 12:41 UTC by an3l

`SIGINT` will abort the connection if `CTRL-C` is pressed x 2 (or more) and the query is long running, what is inline with behavior before the patch - see below. It is checked on Windows too (see jira).
Otherwise it will abort the query (if there is long running query), otherwise it will not exit the client.

##  1. Without the PR
### a) Default: pressing `CTRL-C` aborts the connection
```sql
MariaDB [(none)]> Ctrl-C -- exit!
Aborted
```
### b) For long running query
  - see below (3.) how to simulate
  - same output for killing the query/connection
  - reconnected
##### b.1) Kill query (same with patch)
```sql
MariaDB [(none)]> show databases;
^CCtrl-C -- query killed. Continuing normally.
+--------------------+
| Database           |
+--------------------+
+--------------------+
4 rows in set (4.379 sec)
```

##### b.2) Kill connection
```sql
# 1. query (note that time is 8s)
MariaDB [(none)]> show databases;
^C^CCtrl-C -- query killed. Continuing normally.
Ctrl-C -- query killed. Continuing normally.
+--------------------+
| Database           |
+--------------------+
+--------------------+
4 rows in set (8.716 sec)

# 2. query
MariaDB [(none)]> show databases;
ERROR 2013 (HY000): Lost connection to server during query

# 3. query (note that time is 4s to reconnect, any other query is 1s)
MariaDB [(none)]> show databases;
ERROR 2006 (HY000): Server has gone away
No connection. Trying to reconnect...
Connection id:    15
Current database: *** NONE ***
```

## 2. With the patch
### a) Default:
```sql
MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
```

### b) For long running query 
##### b.1)  Kill query (same as without the patch)
```sql
MariaDB [(none)]> show databases;
^CCtrl-C -- query killed. Continuing normally.
+--------------------+
| Database           |
+--------------------+
+--------------------+
4 rows in set (4.372 sec)

MariaDB [(none)]> ^C
MariaDB [(none)]> exit
Bye
```

##### b.2) Kill connection 
  - 2 or more times `CTRL-C` , connection is aborted
```sql
MariaDB [(none)]> show databases;
^C^C^C^CCtrl-C -- query killed. Continuing normally.
Ctrl-C -- connection killed. Abort. 
+--------------------+
| Database           |
+--------------------+
+--------------------+
4 rows in set (8.479 sec)

Bye
```

## 3. Simulate long running query
#### 1. Add `1 [s]` delay to `docker` network using `tc`: 
```bash
$ tc qdisc show|grep docker
qdisc noqueue 0: dev docker0 root refcnt 2 
$ sudo tc qdisc add dev docker0 root netem delay 1000ms
$ tc qdisc show|grep docker
qdisc netem 8001: dev docker0 root refcnt 2 limit 1000 delay 1.0s
```
#### 2. Start `docker` container and expose port
```bash
$ docker container run --rm -p=3307:3306 --name mariadb-server -e MYSQL_ROOT_PASSWORD=secret -d mariadb:latest
```
#### 3. Start host client with exposed port
```bash
$ ./client/mysql -uroot -psecret -hlocalhost -P3307 --protocol=tcp
```
#### 4. Check queries (takes about `1 [s]`)
```sql
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (1.001 sec)
```

## 4. Problem: `ASAN` bug with patch
   - When using characters after `SIGINT` for slow running queries we hit the bug.
   - Suggestions from reviewer are welcome.
  
```sql
MariaDB [(none)]> show databases;
^CafsdasCtrl-C -- query killed. Continuing normally.
+--------------------+
| Database           |
+--------------------+
+--------------------+
4 rows in set (4.381 sec)

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+
4 rows in set (1.001 sec)

MariaDB [(none)]> ^C
MariaDB [(none)]> exit
Bye

=================================================================
==144227==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x7f8debe1f808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7f8debcfbeac in xmalloc (/lib/x86_64-linux-gnu/libreadline.so.5+0x29eac)
    #2 0x7f8debcf6902 in rl_add_undo (/lib/x86_64-linux-gnu/libreadline.so.5+0x24902)
    #3 0x7f8debcf90ec in rl_insert_text (/lib/x86_64-linux-gnu/libreadline.so.5+0x270ec)
    #4 0x7f8debcfa079 in _rl_insert_char (/lib/x86_64-linux-gnu/libreadline.so.5+0x28079)
    #5 0x7f8debce4455 in _rl_dispatch_subseq (/lib/x86_64-linux-gnu/libreadline.so.5+0x12455)
    #6 0x7f8debce47c0 in readline_internal_char (/lib/x86_64-linux-gnu/libreadline.so.5+0x127c0)
    #7 0x7f8debce4dc4 in readline (/lib/x86_64-linux-gnu/libreadline.so.5+0x12dc4)
    #8 0x55d5f7ea7166 in read_and_execute /home/anel/GitHub/mariadb/server/src/10.4/client/mysql.cc:2133
    #9 0x55d5f7ea4fda in main /home/anel/GitHub/mariadb/server/src/10.4/client/mysql.cc:1297
    #10 0x7f8deb3ad082 in __libc_start_main ../csu/libc-start.c:308
    #11 0x55d5f7ea31ad in _start (/home/anel/GitHub/mariadb/server/build/10.4/client/mysql+0xd51ad)

SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
Aborted (core dumped)
```

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2023-11-28 06:35 UTC, cvicentiu requested changes
Hi @an3l!

I tried your patch with the current client:

```
client/mariadb --protocol=tcp --port 3306 -u root -h localhost
```

Then I try a few queries:
```
MariaDB [(none)]> select sleep(10);
^CCtrl-C -- query killed. Continuing normally.
ERROR 1317 (70100): Query execution was interrupted
MariaDB [(none)]> ^C
MariaDB [(none)]> Bye
```

The last Ctrl-C still exits the client, when it shouldn't. Can you please check why that happens? Then I'll re-review.

2023-12-04 08:21 UTC, an3l commented
Hi @cvicentiu,
I tried to reproduce, but I don't get that error. Tested with 10.4 and 10.6
- 10.4:
```bash
$ ./client/mysql -S /tmp/mysql.sock 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 22
Server version: 10.4.33-MariaDB-debug Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> select sleep(10);
^CCtrl-C -- query killed. Continuing normally.
ERROR 1317 (70100): Query execution was interrupted
MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
MariaDB [(none)]> select 1;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.001 sec)
```
- 10.6
```
 sudo ./client/mariadb -uroot -hlocalhost
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 33
Server version: 10.6.16-MariaDB-1:10.6.16+maria~ubu2004 mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
MariaDB [(none)]> ^C
MariaDB [(none)]> select sleep(10);
^CCtrl-C -- query killed. Continuing normally.
ERROR 1317 (70100): Query execution was interrupted
MariaDB [(none)]> ^C
MariaDB [(none)]> select 2;
+---+
| 2 |
+---+
| 2 |
+---+
1 row in set (0.000 sec)
```
Not sure how you get that.

2024-01-15 15:53 UTC, cvicentiu commented
Hi @an3l!

There is a difference in behaviour between libreadline and libedit, both which implement the readline() function call.

You are getting the right behaviour because the client is compiled with readline. However, this does not work if the client is compiled with libedit.

Try running an ldd on the client `mariadb` binary and then install libedit on your system. Clean your build and config and reconfigure. Now CMake will pick libedit as the preferred library. With that setup, you'll be able to reproduce my problem.

## Actual problem
When libedit is linked instead of readline, sending sigint actually causes the readline call to return null and the follow-up code exits the program.

I've added a commit on top to fix this. https://github.com/MariaDB/server/commit/8ff39e85209d500010ab6542e7ddf5ff74b9e70f

2024-01-22 18:16 UTC, closed without merging

2024-01-22 18:34 UTC, cvicentiu commented
Merged a slightly different patch with https://github.com/MariaDB/server/commit/3cd8875145b2c1dffe1f12510fbf92bf1a8f2fbd.