MDEV-28613 LeakSanitizer caused by I_S query using LIMIT ROWS EXAMINED
MariaDB/server pull request #2831
Opened 2023-11-10 11:39 UTC by Thirunarayanan

- [x] *The Jira issue number for this PR is: MDEV-28613*

## Description
Problem:
========
- InnoDB fails to free the allocated buffer of stored cursor when information schema query is interrupted.

Solution:
=========
- In case of error handling, information schema query should free the allocated buffer to store the cursor.

## How can this PR be tested?
Added the test case

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2023-11-10 11:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2831) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2831) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2831) it.</sub>

2023-11-14 14:10 UTC, dr-m requested changes
In `INFORMATION_SCHEMA.INNODB_SYS_TABLES` there seems to be an additional leak.

Please try to avoid code duplication for the error handling. `goto` is not that evil.

2023-11-14 14:10 UTC, dr-m commented on mysql-test/suite/innodb/r/innodb_stats_fetch.result
> +ERROR HY000: Unknown error
Can we get an outcome that is similar to the following (tested on 10.5 c638051d808a7b29b10e231c9eae97d5909d17f6)?
```
SELECT * FROM seq_1_to_100 limit rows examined 5;
seq
1
2
Warnings:
Warning	1931	Query execution was interrupted. The query exceeded LIMIT ROWS EXAMINED 5. The query result may be incomplete
```
Please make the test case cover all tables whose handling was revised.

2023-11-14 14:10 UTC, dr-m commented on storage/innobase/handler/i_s.cc
> +				DBUG_RETURN(err);
This is missing `mem_heap_free(heap);`. Maybe, declare `int err` in a wider scope, move the release of `dict_sys.mutex` before `mtr_t::commit()` at the end of the function, and add `goto func_exit;` for the error handling.

2023-11-14 14:10 UTC, dr-m commented on storage/innobase/handler/i_s.cc
>  	DBUG_RETURN(0);
Is the `ut_free()` really needed? We do not invoke it in the normal case. When would the cursor position be saved? Could the `ut_free()` be needed also in the normal case?

The `if` around `int err` could be removed here. We could either just `DBUG_RETURN(i_s_dict_fill_sys_tablespaces(…))` or execute the `if` body unconditionally.

2023-11-20 09:57 UTC, dr-m requested changes
I see that we forget to free the `pcur.old_rec_buf` in many functions. It would be better to use a function and a simpler pattern for error handling, like this:
```c++
static int i_s_sys_error_handling(int err, THD *thd)
{
  return thd_kill_level(thd) ? 0 : err;
}
```
and invoke it like this:
```c++
if (err) {
	err = i_s_error_handling(err, thd);
	goto func_exit;
}
```

2023-11-20 09:57 UTC, dr-m commented on mysql-test/suite/innodb/t/innodb_stats_fetch.test
> +SELECT * FROM INFORMATION_SCHEMA.INNODB_SYS_TABLESTATS LIMIT ROWS EXAMINED 5;
Did you mention all these tables in an `.opt` file? `./mtr --embedded` fails:
```
mysqltest: At line 90: query 'SELECT * FROM INFORMATION_SCHEMA.INNODB_SYS_TABLESTATS LIMIT ROWS EXAMINED 5' failed: 1109: Unknown table 'INNODB_SYS_TABLESTATS' in information_schema
```

2023-11-20 09:57 UTC, dr-m commented on storage/innobase/handler/i_s.cc
> +				ut_free(pcur.old_rec_buf);
I think that the `ut_free()` had better be invoked after `func_exit:`, to fix yet another memory leak.

2023-11-20 09:57 UTC, dr-m commented on storage/innobase/handler/i_s.cc
> +				DBUG_RETURN(err);
Add a `goto func_exit` and move the `ut_free()` call there.

2023-11-20 13:08 UTC, dr-m approved these changes
Thank you, this looks OK, except I’d play it safe and add `--disable_result` and `--enable_result` around each `SELECT…LIMIT ROWS EXAMINED` statement.

2023-11-20 13:08 UTC, dr-m commented on mysql-test/suite/innodb/r/innodb_stats_fetch.result
> +SPACE	1
These results could potentially be nondeterministic. Should be disable results for the queries, to be on the safe side?

2023-11-20 13:08 UTC, dr-m commented on mysql-test/suite/innodb/t/innodb_stats_fetch.opt
> +--innodb_sys_tablespaces
Should all `INFORMATION_SCHEMA.INNODB_SYS` plugins be explicitly listed?

2023-11-29 13:37 UTC, Thirunarayanan commented
`commit 84e0c027e03f016da9a7c9dd9ae69fa1303d1ae2 (bb-10.4-MDEV-28613)
Author: Thirunarayanan Balathandayuthapani <thiru@mariadb.com>
Date:   Mon Nov 20 14:58:28 2023 +0530

    MDEV-28613 LeakSanitizer caused by I_S query using LIMIT ROWS EXAMINED
    
    Problem:
    ========
    - InnoDB fails to free the allocated buffer of stored cursor
    when information schema query is interrupted.
    
    Solution:
    =========
    - In case of error handling, information schema query should free
    the allocated buffer to store the cursor.
`

Pushed this PR in 10.4 and above is the commit information.

2023-11-29 13:37 UTC, closed without merging