MDEV-32939 If tables are frequently created, renamed, dropped, a backup cannot be restored
MariaDB/server pull request #2898
Opened 2023-12-05 15:11 UTC by dr-m

- [x] *The Jira issue number for this PR is: MDEV-32939*

## Description
During `mariadb-backup --backup`, a table could be renamed, created and dropped. We could have both `oldname.ibd` and `oldname.new`, and one of the files would be deleted before the InnoDB recovery starts. The desired end result would be that we will recover both `oldname.ibd` and `newname.ibd`.

During normal crash recovery, at most one file operation (create, rename, delete) may require to be replayed from the write-ahead log before the DDL recovery starts.

`deferred_spaces.create()`: In `mariadb-backup --prepare`, try to create the file in case it does not exist.

`fil_name_process()`: Display a message about not found files not only if `innodb_force_recovery` is set, but also in `mariadb-backup --prepare`.

## How can this PR be tested?
It should be possible to write a test case for this using debug injection points. This is work in progress, to be tested with RQG first.

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2023-12-05 16:27 UTC, dr-m commented
The test `mariabackup.rename_during_backup` already includes the following, which is very similar to the scenario that we would like to cover:
```
--let after_copy_test_t5=BEGIN NOT ATOMIC RENAME TABLE test.t5 TO test.t6; CREATE TABLE test.t5(i int) ENGINE INNODB; END
```
I checked an `rr replay` of preparing the backup:
```diff
diff --git a/mysql-test/suite/mariabackup/rename_during_backup.test b/mysql-test/suite/mariabackup/rename_during_backup.test
index d8e40b28941..8f7d21a5f18 100644
--- a/mysql-test/suite/mariabackup/rename_during_backup.test
+++ b/mysql-test/suite/mariabackup/rename_during_backup.test
@@ -49,7 +49,7 @@ exec  $XTRABACKUP --defaults-file=$MYSQLTEST_VARDIR/my.cnf  --backup --target-di
 
 echo # xtrabackup prepare;
 --disable_result_log
-exec $XTRABACKUP  --prepare --target-dir=$targetdir;
+exec rr record $XTRABACKUP  --prepare --target-dir=$targetdir;
 -- source include/restart_and_restore.inc
 --enable_result_log
 
```
It is very similar to the problematic backup data set, but I see that `unlink@plt` is being invoked on `t5.ren` and not `t5.new`. I observed a `FILE_RENAME` record for the `t5` to `t6` (tablespace ID 9) and a `FILE_CREATE` for the new `t5` (tablespace ID 14). I hope that @vaintroub can help me extend the test to cover this scenario.

2023-12-07 11:08 UTC, dr-m commented
I tried to extend a test case so that it would cover the observed scenario, but it did not reproduce the error:
```diff
diff --git a/extra/mariabackup/backup_mysql.cc b/extra/mariabackup/backup_mysql.cc
index 3eb469b08dd..5fd5dabc322 100644
--- a/extra/mariabackup/backup_mysql.cc
+++ b/extra/mariabackup/backup_mysql.cc
@@ -938,6 +938,7 @@ bool lock_tables(MYSQL *connection)
     xb_mysql_query(connection, "SET SESSION wsrep_sync_wait=0", false);
   }
 
+  DBUG_MARIABACKUP_EVENT("before_backup_stage_start", {});
   xb_mysql_query(connection, "BACKUP STAGE START", true);
   DBUG_MARIABACKUP_EVENT("after_backup_stage_start", {});
   xb_mysql_query(connection, "BACKUP STAGE BLOCK_COMMIT", true);
diff --git a/mysql-test/suite/mariabackup/rename_during_backup.result b/mysql-test/suite/mariabackup/rename_during_backup.result
index e071b6b2e21..aaddc30a94b 100644
--- a/mysql-test/suite/mariabackup/rename_during_backup.result
+++ b/mysql-test/suite/mariabackup/rename_during_backup.result
@@ -1,3 +1,4 @@
+CREATE DATABASE best;
 CREATE TABLE t1(i int)   ENGINE INNODB;
 INSERT into t1 values(1);
 CREATE TABLE t2(i int)   ENGINE INNODB;
@@ -61,3 +62,6 @@ SELECT * from t6;
 i
 5
 DROP TABLE t6;
+SELECT * from t7;
+i
+DROP TABLE t7;
diff --git a/mysql-test/suite/mariabackup/rename_during_backup.test b/mysql-test/suite/mariabackup/rename_during_backup.test
index d8e40b28941..bae26499be7 100644
--- a/mysql-test/suite/mariabackup/rename_during_backup.test
+++ b/mysql-test/suite/mariabackup/rename_during_backup.test
@@ -2,6 +2,8 @@
 let $targetdir=$MYSQLTEST_VARDIR/tmp/backup;
 mkdir $targetdir;
 
+CREATE DATABASE best;
+
 CREATE TABLE t1(i int)   ENGINE INNODB;
 INSERT into t1 values(1);
 
@@ -30,9 +32,10 @@ set global innodb_log_checkpoint_now = 1;
 --let before_copy_test_t1=RENAME TABLE test.t1 TO test.t1_renamed
 --let after_copy_test_t2=RENAME TABLE  test.t2 TO test.t2_renamed
 --let after_copy_test_t3=BEGIN NOT ATOMIC RENAME TABLE test.t3 TO test.t3_tmp; INSERT INTO test.t3_tmp VALUES(3); RENAME TABLE test.t3_tmp TO test.t3; END
---let before_copy_test_t4=RENAME TABLE test.t4 TO test.t4_tmp
+--let before_copy_test_t4=BEGIN NOT ATOMIC RENAME TABLE test.t4 TO test.t4_tmp; CREATE TABLE test.t7(i int) ENGINE INNODB; END
 --let after_copy_test_t4=RENAME TABLE test.t4_tmp TO test.t4
 --let after_copy_test_t5=BEGIN NOT ATOMIC RENAME TABLE test.t5 TO test.t6; CREATE TABLE test.t5(i int) ENGINE INNODB; END
+--let before_backup_stage_start=BEGIN NOT ATOMIC RENAME TABLE test.t7 TO best.t8; CREATE TABLE test.t7(i int) ENGINE InnoDB; DROP DATABASE best; END
 
 # Test circular renames
 --let before_copy_test_b=RENAME TABLE test.a to test.tmp, test.b to test.a, test.tmp to test.b
@@ -90,6 +93,9 @@ SELECT * from t5;
 DROP TABLE t5;
 SELECT * from t6;
 DROP TABLE t6;
+SELECT * from t7;
+DROP TABLE t7;
+
 rmdir $targetdir;
 
 
```

2023-12-07 14:46 UTC, dr-m commented
This will require some more work in order to recover one more data set correctly. I am working on it, but I think that the general direction of the patch will remain the same.

2023-12-08 06:09 UTC, Thirunarayanan requested changes
Please request matthias for testing

2023-12-08 06:09 UTC, Thirunarayanan commented on storage/innobase/log/log0recv.cc
> +                             OS_FILE_AIO, OS_DATA_FILE, false, &success);
Missing error handling case?

2023-12-14 10:22 UTC, dr-m commented
I tested 028a35b50640fe94e659d58fe8c7241af2696e89 again, and now all tables of an earlier problematic dataset `data-fts.tar.xz` in [MDEV-32939](https://jira.mariadb.org/browse/MDEV-32939) recover correctly:
```
MariaDB [test]> show tables;
+-------------------+
| Tables_in_test    |
+-------------------+
| t1                |
| t2                |
| t3                |
| t4                |
| t5                |
| t6                |
| t7                |
| table0_innodb_int |
+-------------------+
8 rows in set (0,001 sec)

MariaDB [test]> check table t1,t2,t3,t4,t5,t6,t7;
+---------+-------+----------+----------+
| Table   | Op    | Msg_type | Msg_text |
+---------+-------+----------+----------+
| test.t1 | check | status   | OK       |
| test.t2 | check | status   | OK       |
| test.t3 | check | status   | OK       |
| test.t4 | check | status   | OK       |
| test.t5 | check | status   | OK       |
| test.t6 | check | status   | OK       |
| test.t7 | check | status   | OK       |
+---------+-------+----------+----------+
7 rows in set (0,010 sec)
```
There are 2 further bugs in this area:
* [MDEV-33011](https://jira.mariadb.org/browse/MDEV-33011) `--backup` failure found by @mleich1
* [MDEV-33023](https://jira.mariadb.org/browse/MDEV-33023) crash in `--prepare --export` after running `--prepare`

2023-12-14 12:37 UTC, Thirunarayanan approved these changes

2023-12-14 13:10 UTC, merged