MDEV-31925 mysqld_upgrade --check-if-upgrade-is-needed leaks files
MariaDB/server pull request #2940
Opened 2023-12-18 04:26 UTC by hsser

- [x] *The Jira issue number for this PR is: [MDEV-31925*](https://jira.mariadb.org/browse/MDEV-31925)

## Description
This patch addresses a file leak issue identified in `mysql_upgrade` with the `--check-if-upgrade-is-needed` option. Previously, the execution of `mysql_upgrade` with this flag would leave temporary files in the system's temp directory. This patch ensures that any temporary files created during the `mysql_upgrade `process are properly cleaned up, thus maintaining a cleaner system environment.

## How can this PR be tested?

The patch includes an updated test case that verifies the absence of temporary files after running `mysql_upgrade` with the `--check-if-upgrade-is-needed` option. This test should pass without any temporary files being left behind in the temp directory.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [x] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/11.0/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2023-12-18 05:09 UTC, grooverdan requested changes
Thanks for the contribution. In addition to the above comments, can you rebase this on 10.4, our earliest maintained version.

Can you squash the 3 commits together.
Also with the commit message can you describe the high level problem and fix.

2023-12-18 05:09 UTC, grooverdan commented on mysql-test/t/mysql_upgrade_file_leak.test
> +die "Test failed: Found temporary file left by mysql_upgrade\n" if $temp_file_found;
my perl isn't the best but could this be just `die ... if (!glob "mysql_upgrade*");`?

2023-12-18 05:09 UTC, grooverdan commented on mysql-test/t/mysql_upgrade_file_leak.test
> +--echo End of test
`--echo End of 10.4 tests` for new convention.

2023-12-18 05:09 UTC, grooverdan commented on mysql-test/t/mysql_upgrade_file_leak.test
> +-- source include/have_partition.inc
can omit these except the first one right?

2023-12-18 05:09 UTC, grooverdan commented on mysql-test/t/mysql_upgrade_file_leak.test
> +set sql_mode="";
unused?

2023-12-18 07:56 UTC, an3l commented
Hi,
just to help you with Git to update to 10.4.
It should go like this:
```bash
# Create 10.4 if not exists (where upstream is name of remote upstream or origin `git remote -v`)
$ git branch 10.4 upstream/10.4
# Work on new branch 
$ git checkout 10.4
$ git checkout -b <my-10.4-branch>
# Cherry-pick what you have done
$ git cherry-pick <commit-hash>
# Push changes without closing PR
$ git push <my-10.4-branch>:10.2-31925 -f
```
Change the base in GitHub from 10.2 to 10.4.

2023-12-18 08:05 UTC, hsser commented
@an3l Thank you so much for helping me out with the Git rebase mess. Seriously, I was pretty lost there, and your guidance was a lifesaver.

2023-12-18 19:42 UTC, hsser commented
> Thanks for the contribution. In addition to the above comments, can you rebase this on 10.4, our earliest maintained version.
> 
> Can you squash the 3 commits together. Also with the commit message can you describe the high level problem and fix.

@grooverdan Thank you for your comprehensive feedback on the test case. Based on your suggestions, I have made the necessary updates and amendments. Additionally, I have rebased the branch and squashed the commits to maintain a clean history.

2023-12-19 05:27 UTC, grooverdan commented
Thank you, sorry one last request - can you put the MDEV number at the top of the commit message in the title and then git push --force it to update this PR again.

Looks very clean. Thanks @an3l for helping witg rebase instructions,

2023-12-19 06:10 UTC, grooverdan approved these changes
Thank you.

2023-12-19 08:29 UTC, LinuxJedi approved these changes

2023-12-19 08:30 UTC, merged