MDEV-18478
MariaDB/server pull request #2970
Opened 2023-12-28 14:22 UTC by spetrunia

- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
TODO: fill description here

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2023-12-30 09:20 UTC, Olernov requested changes

2023-12-30 15:14 UTC, spetrunia commented on sql/sql_explain.cc
> +    print_r_icp_filtered(handler_for_stats, tracker, writer);
No it is not.  Note the "outdated" - you're looking at the old version of commit (not sure how)
![image](https://github.com/MariaDB/server/assets/2734550/b8522904-128a-4a9f-842e-588861f0e310)

2024-01-02 08:24 UTC, spetrunia commented
@Olernov , I believe I have addressed all of the review input.

2024-01-04 06:40 UTC, Olernov commented
OK, thanks! No more comments from me.

2024-01-04 12:50 UTC, Olernov approved these changes

2025-02-27 10:32 UTC, closed without merging