Make SESSION_USER() comparable with CURRENT_USER()
MariaDB/server pull request #2985
Opened 2024-01-08 18:18 UTC by christian7007

Update `SESSION_USER()` behaviour to be comparable with `CURRENT_USER()`. `SESSION_USER()` will return the user and host columns from `mysql.user` used to authenticate the user when the session was created.

Historically `SESSION_USER()` was an alias of `USER()` function. The main difference with `USER()` behaviour after this changes is that `SESSION_USER()` now returns the host column from `mysql.user` instead of the client host or ip.

NOTE: `SESSION_USER_IS_USER` old mode is added to make the change backward compatible.

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
TODO: fill description here

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2024-01-08 18:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=2985) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=2985) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=2985) it.</sub>

2024-01-08 18:20 UTC, christian7007 commented
The changes on this PR were previously discussed with @vuvova and @grooverdan at: https://github.com/MariaDB/server/pull/2928

2024-01-10 01:17 UTC, christian7007 commented
@vuvova regarding your comment about optional parenthesis here: https://github.com/christian7007/server/commit/4c9ec8155eb9d72edc4a30560ff941d70e634eb5#r135239559.

The first version I pushed for this PR allowing option parenthesis broke `main.parser` test at:
https://github.com/MariaDB/server/blob/c0c1c80346b926ea1358aa512374d72d513299b0/mysql-test/main/parser.test#L116

Maybe I'm missing something, but after some research my understanding is that the failure came from supporting `SESSION_USER` with optional parenthesis (if we add `SESSION_USER_SYM` as `keyword_sp_var_and_label` using `optional_braces` it will cause ambiguity and will make the parser building to fail). This was not supported before, and as adding this will break backward compatibility I pushed a new version for the changes making parenthesis mandatory for `SESSION_USER()` again.

Please, let me know if you think I'm missing something or if you think there is a better way of addressing this.

2024-01-10 01:18 UTC, christian7007 commented
I also updated some MTR tests, there are still some CI failures but after looking at them I don't think they are related with my changes.

2024-01-12 21:57 UTC, vuvova commented
I've marked MDEV-30908 as being IN-REVIEW, assigned to myself. But I'll only look at it next month. There's still enough time for it to get into the next release (deadline is mid-March).

2024-04-07 04:25 UTC, ottok commented
We know you @vuvova are busy, but perhaps you could do a superficial review to let us know if you agree with this change in principle?

2024-06-06 16:09 UTC, vuvova requested changes
Looks fine to me. Just rebase on top of 11.6, you'll have old-mode related conflicts, and that's it.

2024-06-06 16:09 UTC, vuvova commented on sql/sys_vars.cc
> +  "SESSION_USER_IS_USER",
when you'll rebase it on top of 11.6, you'll see a conflict here, see how the new old mode `OLD_FLUSH_STATUS` was added and add yours in the same way with a correct deprecation version.

2024-06-06 16:09 UTC, vuvova commented on sql/item_strfunc.h
> +  }
`get_copy()` ?

2024-06-06 16:09 UTC, vuvova commented on sql/item_strfunc.h
> +  bool check_vcol_func_processor(void *arg) override
doesn't seem to be necessary? `Item_func_sysconst` (two classes up the hierarchy) has exactly that.

2024-08-22 21:01 UTC, vuvova commented
@christian7007 just a reminder. this is still waiting. 11.7 window is closing in less than three weeks.

2024-08-23 12:18 UTC, vuvova approved these changes
looks good, thanks! A couple of minor comments, if you won't fix them by the time I'll merge it (in about two weeks), I'll fix them myself, so feel free to ignore them

2024-08-23 20:13 UTC, christian7007 commented
Hey @vuvova, I just pushed a new version with the two minor changes, I'm not sure if it being a reserved word needs any other adjustment, I just updated the comment. Let me know if something else is needed.

2024-08-23 20:36 UTC, vuvova commented
thanks! no, it didn't need any adjustments in the code, we don't feel that we have to reserve in MariaDB every keyword that is reserved in the SQL standard. It's indeed just a comment, clarifying that the keyword is part of the SQL standard and that it's reserved there. Kind of a keyword provenance. Nothing more.

2024-08-23 21:23 UTC, christian7007 commented
Thanks for the explanation! I can see some CI tests failing, but looking at the failures it doesn't look related with my changes and I can see the tests are also unstable in the target branch. I understand that this is ready to merge, but please let me know if you need anything else from my side.

2024-10-02 18:52 UTC, ottok commented
A copy of this exists on branch https://github.com/MariaDB/server/tree/bb-11.7-MDEV-30908-session-user

2024-10-04 11:22 UTC, merged