Factor TABLE_LIST creation from add_table_to_list
MariaDB/server pull request #3196
Opened 2024-04-12 18:00 UTC by DaveGosselin-MariaDB

Ideally our methods and functions should do one thing, do that well, and do only that.  add_table_to_list does far more than adding a table to a list, so this commit factors the TABLE_LIST creation out to a new TABLE_LIST constructor.  It then uses placement new() to create it in the correct memory area (result of thd->calloc). Benefits of this approach:
 1. add_table_to_list now returns as early as possible on an error
 2. fewer side-effects incurred on creating the TABLE_LIST object
 3. TABLE_LIST won't be calloc'd if copy_to_db fails
 4. local declarations moved closer to their respective first uses
 5. improved code readability and logical flow Also factored a couple of other functions to keep the happy path more to the left, which makes them easier to follow at a glance.

2024-04-12 18:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=3196) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=3196) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=3196) it.</sub>

2024-04-14 21:57 UTC, vuvova requested changes

2024-04-14 21:57 UTC, vuvova commented on sql/table.cc
> +                       LEX_STRING *_option)
Please, try to stick to the coding style which is used elsewhere. In particular, constructor arguments don't typically start with an underscore.

2024-04-14 21:57 UTC, vuvova commented on sql/table.cc
> +  ptr->db= _db;
you don't really need this `ptr->` after you've copied the code here. It would look more natural without

2024-04-14 21:57 UTC, vuvova commented on sql/table.cc
> +  ptr->sequence=      MY_TEST(table_options & TL_OPTION_SEQUENCE);
all these MY_TEST are redundant

2024-04-15 13:43 UTC, DaveGosselin-MariaDB commented on sql/table.cc
> +  ptr->sequence=      MY_TEST(table_options & TL_OPTION_SEQUENCE);
Removed.

2024-04-15 18:19 UTC, vuvova approved these changes
ok to push

2024-04-16 14:09 UTC, merged