MDEV-33863: New mysqladmin command tls-info
MariaDB/server pull request #3247
Opened 2024-05-08 14:38 UTC by 9EOR9

- [x] *The Jira issue number for this PR is: MDEV-3383*

## Description
Added a new command tls-info for mysqladmin client tool, which provides information for the TLS connection in use.

## Release Notes
mysqladmin: Added a new command `tls-info` which returns the following information:
- TLS ciphersuite
- TLS protocol
- Peer certificate information:
  - Version
  - Subject
  - Issuer
  - Valid not before/not after
  - SHA256 fingerprint

## How can this PR be tested?
There is no test for, since the output depends on the certificate used by peer.
Feature can be tested by executing mysqladmin with command tls-info.

## Basing the PR against the correct MariaDB version
- [ X] *This is a new feature and the PR is based against the latest MariaDB development branch.*
- [ ] *This is a bug fix and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2024-05-08 14:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=3247) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=3247) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=3247) it.</sub>

2024-05-09 01:10 UTC, grooverdan approved these changes
Cosmetic changes but otherwise ok.
So as a new feature this will go into testing for the 11.6 release.

2024-05-14 18:43 UTC, tonychen2001 commented on client/mysqladmin.cc
> +	        my_printf_error(0, "Unable to retrieve peer certificate", 0);
Just for verbosity the [CODING STANDARDS](https://github.com/MariaDB/server/blob/11.5/CODING_STANDARDS.md) link in the PR template provides the coding style guideline and coding standards in general.

2024-05-14 18:50 UTC, tonychen2001 commented on mysql-test/main/tls_version1.opt
> ---tls_version=TLSv1.0
Nice 😄

2024-07-23 12:30 UTC, vuvova requested changes
please remove all changes to unrelated submodules from your commit

2024-07-23 12:30 UTC, vuvova commented on client/client_priv.h
> +  OPT_TLS_CERT_INFO,
what is that for?

2024-07-23 12:30 UTC, vuvova commented on client/mysqladmin.cc
> +        printf("Cipher suite:\t%s\n", mysql_get_ssl_cipher(mysql));
why not to fix it?
```
if (const char *cipher= mysql_get_ssl_cipher(mysql))
{
```

2024-07-23 12:30 UTC, vuvova commented on client/mysqladmin.cc
> +          printf("SHA256 fingerprint: %s\n", info->fingerprint);
use openssl format, perhaps?
```
Version: 3 (0x2)
Issuer: CN = cacert, C = FI, ST = Helsinki, L = Helsinki, O = MariaDB
Validity
    Not Before: Mar  3 03:03:03 2020 GMT
    Not After : Feb 27 03:03:03 2040 GMT
Subject: C = FI, ST = "state or province within country, in other certificates in this file it is the same as L", L = "location, usually an address but often ambiguously used", O = "organization name, typically a company name", OU = "organizational unit name, a division name within an organization", CN = localhost
SHA256 Fingerprint=4B:EE:BB:12:6D:30:1A:B2:2A:4A:F8:6D:82:7F:63:44:1F:8F:F4:6B:D3:F2:CA:68:0B:D5:E3:5D:1C:47:A7:16
```

2025-01-20 07:41 UTC, closed without merging