Revert "MDEV-32935: Remove unneeded CMAKE_SYSTEM_PROCESSOR parameter …
MariaDB/server pull request #3293
Opened 2024-05-29 13:59 UTC by LinuxJedi

…from Debian"

This reverts commit 6914b7804dd29b71f9a85a120f6352d8cd855e38.

With the MDEV-32935 change, building on 32bit Linux with a 64bit CPU causes CMAKE_SYSTEM_PROCESSOR to detect 64bit. This then triggers things such as ColumnStore to build, which definitely should not build on a 32bit platform.

2024-05-29 14:06 UTC, LinuxJedi commented
Assigned @illuusio to check this as I don't want this to break MDEV-32936.

2024-05-29 21:57 UTC, grooverdan requested changes
reject: We shouldn't hack our way around not wanting to build 32bit as a cross compile (which is what 32 bit builds on 64 bit OS are).

2024-05-30 10:10 UTC, vuvova commented
@grooverdan cmake must know whether it's a 32-bit build or a 64-bit build. @LinuxJedi says with this PR that the correct way of determining it is to examine the `CMAKE_SYSTEM_PROCESSOR` variable. If you think it's a hack, you need tell what you think is the correct way of getting this information.

2024-05-30 12:08 UTC, vaintroub commented
I think the correct way to determine bitness of the build is to examine CMAKE_SIZEOF_VOID_P variable, like it is done in multiple places https://cmake.org/cmake/help/latest/variable/CMAKE_SIZEOF_VOID_P.html

2024-05-30 13:06 UTC, vuvova commented
it's not only that. ColumnStore only supports amd64 (x86_64) and arm64 (aarch64). So "any 64-bit" is not good enough.

2024-05-30 13:52 UTC, vaintroub commented
I think for the purpose of excluding columnstore from 32bit builds, it would work pretty well. CMAKE_SIZEOF_VOID_P is more reliably than whatever people pass in CMAKE_SYSTEM_PROCESSOR

2024-05-30 20:57 UTC, vuvova commented
Currently ColumnStore has
```cmake
IF(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR
CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64" OR
CMAKE_SYSTEM_PROCESSOR STREQUAL "aarch64")
```

Do you suggest to replace it with  `CMAKE_SIZEOF_VOID_P EQUAL 8` ? It'll allow ppc64. Or to add the new condition with `AND`? Still relying on whatever people pass in `CMAKE_SYSTEM_PROCESSOR`?

2024-05-30 21:20 UTC, vaintroub commented
At least testing for CMAKE_SIZEOF_VOID_P EQUAL 8 is better than now. Much better in fact. If  the know they do not build on 32bit.
All these architectures are some predefined constants in gcc (I assume they restrict themselves only to at most gcc and clang). 
So they can write a test to test for those __x86_64_ and whatever other architecture they probably already use in their code.

2024-05-30 23:27 UTC, grooverdan commented
`DEB_HOST_ARCH` isn't a correctly formatted processor variable. It contains Debian's weird interpretations (string differences - ppc64el e.g. for a little endian pun on everyone's expense) of what architecture is that don't actually occur on a native build.  To use this hack we'd be maintaining multiple hacks of what architecture is throughout the codebase and `IF(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86_64" OR CMAKE_SYSTEM_PROCESSOR STREQUAL "amd64"` is a example of this hack. We've got enough different interpretations via Windows and BSDs so lets not add another one.

A proper cmake cross compilation would have the right value and also ensure the other CMake variables include the actual representation of the target hardware.

@illuusio  is looking at something like `setarch i686 eatmydata dpkg-buildpackage  ...` for debian/autobake-deb.sh which fakes the `uname -m`  output. Apparently what Debian does in its build architecture for all the supposed Intel/AMD 32bit users out there.

2024-05-30 23:58 UTC, grooverdan commented
or maybe like http://crossqa.debian.net/src/mariadb in autobake-deb.sh when there's not a native arch.
```
dpkg-buildpackage --sanitize-env -ai386 -Pcross,nocheck -us -uc -B -rfakeroot --jobs-try=1
```

2024-05-31 13:43 UTC, vuvova commented
@grooverdan I'm not saying `CMAKE_SYSTEM_PROCESSOR` is the correct way of determining the target architecture. I'm just saying, I'm sure there is one.

@vaintroub basically suggests TRY_COMPILE with, like
```c
#if !defined(__x86_64__) && !defined(__aarch64__)
#error
#endif
```
which will definitely work and perhaps we'll have to resort to this. But I'd be very surprised if cmake doesn't provide any builtin way of checking the target architecture.

2024-06-03 07:21 UTC, LinuxJedi commented
> reject: We shouldn't hack our way around not wanting to build 32bit as a cross compile (which is what 32 bit builds on 64 bit OS are).

This explicitly wasn't for a 64bit OS, but the method CMake uses can still detect a 64bit CPU on a 32bit OS when you are not cross-compiling.

2024-06-11 03:34 UTC, grooverdan commented
close since #3303 has fixed it?

2024-06-26 08:06 UTC, LinuxJedi-Test approved these changes
Test Review

2024-06-26 08:07 UTC, closed without merging