[MDEV-33834] Extend audit plugin to include tls_version and tls_version_length variables
MariaDB/server pull request #3502
Opened 2024-09-05 00:56 UTC by keeper

MDEV: https://jira.mariadb.org/browse/MDEV-33834

## Description
This is the continuous work of https://github.com/MariaDB/server/pull/3175.

Add tls_version and tls_version_length variables to the audit plugin so they can be logged. This is useful to help identify suspicious or malformed connections attempting to use unsupported TLS versions. A log with this information will allow to detect and block more malicious connection attempts.

Users with 'server_audit_events' empty will have these two new variables automatically visible in their logs, but if users don't want them, they can always configure what fields to include by listing the fields in 'server_audit_events'.

In connection event, The TLS version will be populated in `object` field
in key=value format, and the key-value pair will be omitted when the
value is empty.

To ensure the MTR test result matches in all environments, the TLS
version string is replaced with a general `TLS_VERSION` to avoid the MTR
test failing unexpectedly. The regex is based on the output of
`SSL_get_version()` function in latest OpenSSL library (v3.3), which
returns 10 possible values[1]:
  - SSLv3
  - TLSv1
  - TLSv1.1
  - TLSv1.2
  - TLSv1.3
  - DTLSv0.9
  - DTLSv1
  - DTLSv1.2
  - QUICv1
  - unknown

All new code of the whole pull request, including one or several files
that are either new files or modified ones, are contributed under the
BSD-new license. I am contributing on behalf of my employer Amazon Web
Services, Inc.

[1]: https://docs.openssl.org/3.2/man3/SSL_get_version/

## Release Notes
None. This just adds more possibilities for users.

## How can this PR be tested?

Modified the server audit plugin to include this new info, and updated the server audit plugin MTR tests.

## Basing the PR against the correct MariaDB version
- [X] *This is a new feature and the PR is based against the latest MariaDB development branch.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

## Copyright

All new code of the whole pull request, including one or several files that are either new files or modified ones, are contributed under the BSD-new license. I am contributing on behalf of my employer Amazon Web Services, Inc.

2024-09-05 00:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=3502) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=3502) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=3502) it.</sub>

2024-09-05 00:57 UTC, keeper commented
This is the rework of https://github.com/MariaDB/server/pull/3175 and the issues in the PR has been addressed in this one, feel free to close previous PR, thank you.

2024-10-02 20:32 UTC, vuvova commented
See the discussion in https://jira.mariadb.org/browse/MDEV-33834

2024-12-17 05:20 UTC, ottok commented
The original PR #3502 and [MDEV-33834](https://jira.mariadb.org/browse/MDEV-33834) was filed in in April 2024. As the year is coming to an end, can you advice us on what we should do to get traction on this relatively straightforward feature to have TLS connection version included in the logs?

2024-12-17 09:23 UTC, vuvova commented
It's explained in [this Jira comment](https://jira.mariadb.org/browse/MDEV-33834?focusedCommentId=291141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-291141) — we need an architectural design and decision of how we'll be extending the Audit API. Adding new fields ad hoc to various structures is one possible approach, but may be it's not the best one.

2024-12-17 15:31 UTC, ottok commented
I think it would make more sense to just add that field as the PR has been ready since April, instead of aiming for a new API and forcing a dependency on 11 year old [MDEV-5313](https://jira.mariadb.org/browse/MDEV-5313) which is unlikely to happen.

2025-01-07 04:28 UTC, ottok commented
Do you @cvicentiu have any comments about this one?

2025-03-03 19:38 UTC, ottok commented
Could this be merged into 'main' now so it ships in MariaDB 12.0?

2025-03-09 14:02 UTC, vuvova requested changes
Sorry for delay, let's get it merged.

There were few minor comments, do you want to change the patch accordingly? If you'd like I can make these changes myself, less work for you.

2025-03-09 14:02 UTC, vuvova commented on plugin/server_audit/server_audit.c
> +                     event->status, cn->tls_version_length, cn->tls_version);
After many back-and-forths we came back to the original idea. Please, just print tls version here, without the  TLS_VERSION_KEY=

2025-03-09 14:02 UTC, vuvova commented on plugin/server_audit/server_audit.c
> +    ",%.*s,%.*s,%d", cn->db_length, cn->db, obj_len, tls_obj, event->status);
why is it in the middle, I thought, the idea was to have a new column at the end of the row, for compatibility reasons?

2025-03-16 19:09 UTC, vuvova commented
Tomorrow's the last day, if there won't be a patch we can accept and you won't say "just fix it yourself", it will miss 12.0

2025-03-16 20:54 UTC, keeper commented
> Tomorrow's the last day, if there won't be a patch we can accept and you won't say "just fix it yourself", it will miss 12.0

Hey, sorry for late response, I'll address the feedback today

2025-03-16 21:14 UTC, keeper commented on plugin/server_audit/server_audit.c
> +    ",%.*s,%.*s,%d", cn->db_length, cn->db, obj_len, tls_obj, event->status);
This implementation was based on a previous discussion that uses `object` field with KEY-VALUE pair (see: https://jira.mariadb.org/browse/MDEV-33834?focusedCommentId=287819&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-287819)

I'll change it to:
```
[timestamp],[serverhost],[username],[host],[connectionid],[queryid],[operation],[database],[object],[retcode].[tls-version]

20190710 00:05:30,localhost.localdomain,root, localhost,2,0,CONNECT,testdb,,0,TLSv1.2
```

2025-03-16 23:10 UTC, keeper commented on mysql-test/suite/plugins/t/server_audit.test
> +--replace_regex /[0-9]* [0-9][0-9]:[0-9][0-9]:[0-9][0-9]\,[^,]*\,/TIME,HOSTNAME,/ /\,[1-9][0-9]*\,/,1,/ /\,[1-9][0-9]*/,ID/ /((SSL|D?TLS|QUIC)v[0-9](\.[0-9])?|unknown)/TLS_VERSION/
I used option 2 in the latest version

2025-03-19 18:18 UTC, vuvova commented on plugin/server_audit/server_audit.c
> +    ",%.*s,%.*s,%d", cn->db_length, cn->db, obj_len, tls_obj, event->status);
No, you were right, it should've been in the object column. It was my mistake. I'll fix it, please, never mind

2025-03-19 19:04 UTC, vuvova commented on plugin/server_audit/server_audit.c
> +    ",%.*s,%.*s,%d", cn->db_length, cn->db, obj_len, tls_obj, event->status);
You were right, it should've been in the "object" column. My mistake, sorry. I'll fix it, never mind

2025-04-04 17:56 UTC, tonychen2001 commented on include/mysql/plugin_audit.h
> +  unsigned int tls_version_length;
Should we use MYSQL_CONST_LEX_STRING here?

2025-04-04 18:05 UTC, vuvova commented on include/mysql/plugin_audit.h
> +  unsigned int tls_version_length;
No, let's be consistent

2025-05-03 11:23 UTC, vuvova commented
pushed into 12.0 thanks

2025-05-03 11:23 UTC, closed without merging

2025-05-03 22:34 UTC, ottok commented
This was targeting 'main' already, isn't that same as 12.0 now? Why close this manually when you could have just rebased/merged it and grant the contributor their sweet "Merged" badge?

I can't find the commit now. Using `git pull` from this branch or GitHub features would show the git commit references automatically.

2025-05-03 22:37 UTC, ottok commented
Found it now in 2b464774f240a18e1ff43cd18938a72a2d042e1f and related #3324 merged in manually in a way that neither git nor GitHub knows about it in 1aba30b8f990148ac23f0069b59976920acd3d61.

2025-05-03 23:22 UTC, vuvova commented
> This was targeting 'main' already, isn't that same as 12.0 now? Why close this manually when you could have just rebased/merged it and grant the contributor their sweet "Merged" badge?

A contributor didn't allow the PR to be modified by maintainers, so I wasn't able to rebase it