MDEV-34316 Ignore the NOCOPY keyword in stored routine parameters when sql_mode=ORACLE
MariaDB/server pull request #3517
Opened 2024-09-13 03:30 UTC by wong-github1

- [x] *The Jira issue number for this PR is: MDEV-34316

## Description
During sql_mode=ORACLE, ignore the NOCOPY keyword in stored routineparameters. The optimization (pass-by-reference instead of pass-by-value) helping to avoid value copying will be done in a separate task when needed.

## Release Notes
Ignore the NOCOPY keyword in stored routine parameters when sql_mode=ORACLE

## How can this PR be tested?

mysql-test/mtr sp-ignore_nocopy

## Basing the PR against the correct MariaDB version
- [x] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [ ] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2024-09-13 03:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=3517) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=3517) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: sts-kokseng.wong<br/>:x: wong-github1<br/><hr/>**sts-kokseng.wong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=3517) it.</sub>

2024-09-13 06:15 UTC, LinuxJedi commented
Hi @wong-github1,

Unfortunately this is causing test failures, this is because the `NOCOPY` keyword is also used for `ALTER TABLE`, for example:

```sql
ALTER TABLE t1 MODIFY d DOUBLE DEFAULT 10, ALGORITHM=NOCOPY
```

2024-09-13 11:45 UTC, wong-github1 commented
> Hi @wong-github1,
> 
> Unfortunately this is causing test failures, this is because the `NOCOPY` keyword is also used for `ALTER TABLE`, for example:
> 
> ```sql
> ALTER TABLE t1 MODIFY d DOUBLE DEFAULT 10, ALGORITHM=NOCOPY
> ```

Hi @LinuxJedi (Andres),

Thanks you so much in pointing out the error. I have just fixed it.

2024-09-26 22:11 UTC, FooBarrior requested changes
Hello @wong-github1! Thank you for your efforts. 

For the ORACLE compatibility mode we have an compat/oracle suite. I think you can put your tests in the sp-param.test file in that suite.

Also I think we can avoid an extra switch in your ALTER TABLE fix. Can you please update it according to my suggestion?

Kind regards.

2024-09-30 03:46 UTC, wong-github1 commented on sql/sql_yacc.yy
> +%type <num> alter_algorithm_option_is_kwd
Updated.

2024-09-30 03:46 UTC, wong-github1 commented on sql/sql_yacc.yy
> +           DEFAULT    { $$ = 0; }
Updated.

2024-09-30 03:50 UTC, wong-github1 commented
Hi @FooBarrior ,
Thanks for your review. I have made the corresponding revision.
Need your help to review again and once again, thank you.

2024-10-01 10:45 UTC, FooBarrior approved these changes

2024-10-03 22:17 UTC, merged

2024-10-22 20:29 UTC, FooBarrior commented
Hello again @wong-github1! 

Our QA has found a bug within this patch: [MDEV-35229](https://jira.mariadb.org/browse/MDEV-35229). Can you please take a look?

The bug is serious and the priority is high, so would be nice if you can take a look as soon as possible.

If any questions, reach me out in MariaDB's zulip:
https://mariadb.zulipchat.com/#user/127697

Best regards

Nikita