MDEV-30645 - Implement generalized triggers 2
MariaDB/server pull request #3551
Opened 2024-09-25 17:48 UTC by andremralves

- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
Another approach for the implementation of Generalized Triggers with DROP TRIGGER ... ON ALL SERVER.

## Release Notes
TODO: What should the release notes say about this change?
Include any changed system variables, status variables or behaviour. Optionally list any https://mariadb.com/kb/ pages that need changing.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [ ] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2026-05-28 08:19 UTC, gkodinov requested changes
This is a preliminary review. 
Please add a message compliant with the MariaDB coding standards to the commit. Also, please rebase on the latest main branch. And make sure all of the tests on all buildbot hosts are not failing because of your change.

2026-05-28 09:32 UTC, vuvova commented
@gkodinov, eh, no sorry. Please ask @dmitryshulga for the status of this work.

2026-06-18 10:25 UTC, gkodinov commented
@vuvova, there's been no activity known to me or confirmed by anybody on this PR. @dmitryshulga included. I'm converting this to a draft pull request. Please re-open when/if the work on this resumes.

2026-06-19 19:12 UTC, vuvova commented
Thanks! The work was continued in #5034 by @dmitryshulga.

2026-06-19 19:12 UTC, closed without merging