MDEV-34900: Fix stage names for profiling
MariaDB/server pull request #3594
Opened 2024-10-24 13:28 UTC by SaitejSamudrala

- [x] *The Jira issue number for this PR is: MDEV-______*

## Description
TODO: fill description here

## Release Notes
TODO: What should the release notes say about this change?
Include any changed system variables, status variables or behaviour. Optionally list any https://mariadb.com/kb/ pages that need changing.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [ ] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [ ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ ] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

- This PR addresses MDEV-34900 by renaming stage_executing to "Prepare for executing" and stage_sending_data to "executing" in JOIN::exec_inner() to better reflect the actual process during profiling.

2024-10-25 01:56 UTC, grooverdan requested changes
Thank you for your first contribution to MariaDB.

Code looks correct.

If you `git grep 'Sending data'` you'll see quite a few test cases that are dependant on this test. Likely they will fail.  Test can be re-recorded with `mysql-test/mtr --record innodb.innodb-lock` as example.  This will update a `.result` file. `git commit --amend {these files}` to include them in your previous commit message and `git push --force` to update this PR.

Also improve the commit message by starting the the MDEV, like you did for the PR title. Include in the message the rational for the change (straight from JIRA entry is fine).

Once that happens, we'll look again at how the CI ran against these changes.

FYI: I looked at `stage_sending_data` in sql/sql_admin.cc and I think it can stay as is.

2024-10-25 05:07 UTC, cvicentiu approved these changes
Approve for running in CI

2024-10-25 06:35 UTC, RazvanLiviuVarzaru commented
@SaitejSamudrala Thank you for your contribution! Can you also please sign the `Contributor License Agreement`? Thanks!

2024-10-25 09:59 UTC, SaitejSamudrala commented
> Thank you for your first contribution to MariaDB.
> 
> Code looks correct.
> 
> If you `git grep 'Sending data'` you'll see quite a few test cases that are dependant on this test. Likely they will fail. Test can be re-recorded with `mysql-test/mtr --record innodb.innodb-lock` as example. This will update a `.result` file. `git commit --amend {these files}` to include them in your previous commit message and `git push --force` to update this PR.
> 
> Also improve the commit message by starting the the MDEV, like you did for the PR title. Include in the message the rational for the change (straight from JIRA entry is fine).
> 
> Once that happens, we'll look again at how the CI ran against these changes.
> 
> FYI: I looked at `stage_sending_data` in sql/sql_admin.cc and I think it can stay as is.

Timeout in wait_condition.inc for select count(*) = 1 from information_schema.processlist
where state = 'Sending data' and
info = 'SELECT * FROM t1 FOR UPDATE'
Id	User	Host	db	Command	Time	State	Info	Progress
4	root	localhost	test	Sleep	30		NULL	0.000
5	root	localhost	test	Query	30	Executing	SELECT * FROM t1 FOR UPDATE	0.000
6	root	localhost	test	Query	0	starting	show full processlist	0.000
Hi, this is the changes in the .result file I am getting after running `mysql-test/mtr --record innodb.innodb-lock` is this the intended result or am I making a mistake here.Thanks.

2024-10-25 18:09 UTC, grooverdan commented
Ah, if related to the state, `Sending data` is in a .test file change this, then re-record. (hopefully result change will just be a text change.

2025-02-28 02:03 UTC, grooverdan commented
resolved merge confict (was just whitespace).

noticed scripts/sys_schema/views/p_s/*.sql that include "Sending data" but these where only in SQL comments.

The list of tests (with bash expansion) is:
*  innodb_mysql_lock2  innodb.create_select innodb.deadlock_in_subqueries_join innodb.innodb-blob innodb.innodb-lock innodb.innodb-timeout  innodb.lock_isolation innodb.xa_recovery  perfschema.processlist_57  perfschema.stage_mdl_table  perfschema.setup_actors rpl.rpl_parallel_autoinc rocksdb.locking_issues_case{1_1_rc,1_1_rr,1_2_rc,1_2_rr,2_rc,2_rc_lsr,2_rr,2_rr_lsr,3_rc,3_rr,4_rc,4_rr,5_rc,5_rr,6_rc,6_rr,7_rc,7_rc_lsr,7_rr,7_rr_lsr}
* innodb-blob is debug build.

I've addressed the Failing tests:
* perfschema.stage_mdl_table rocksdb.locking_issues_case4_rc rocksdb.locking_issues_case3_rc rocksdb.locking_issues_case4_rr rocksdb.locking_issues_case3_rr rpl.rpl_parallel_autoinc rocksdb.locking_issues_case5_rr rocksdb.locking_issues_case6_rc rocksdb.locking_issues_case6_rr innodb.create_select innodb.lock_isolation innodb.innodb-lock innodb.deadlock_in_subqueries_join innodb.xa_recovery

2025-04-27 11:57 UTC, vuvova requested changes
This is incorrect. Unfortunately, the description was rather confusing. See comments in [MDEV-34900](https://jira.mariadb.org/browse/MDEV-34900)

What needs to be done is to make sure that `stage_sending_data` isn't set too early. It must be done right before, well, sending data. If MariaDB needs to do a lot of work on the query before the first result row is sent to the client, this must not be under "sending data".

2025-08-19 16:19 UTC, vuvova commented
No activity since April, so closing. Please comment if you want to reopen it

2025-08-19 16:19 UTC, closed without merging