MDEV-35614 json unquote utf8mb4
MariaDB/server pull request #3694
Opened 2024-12-12 09:10 UTC by grooverdan

- [x] *The Jira issue number for this PR is: MDEV-35614*

## Description

No smiley emojis in JSON_UNQUOTE.

## Release Notes

Smilieys are back.

## How can this PR be tested?

basic test case there. Need to do more (and probably split out non-json commits)

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [X] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [X] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [X] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2025-04-10 06:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MariaDB/server?pullRequest=3694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/MariaDB/server?pullRequest=3694) before we can accept your contribution.<br/>**2** out of **11** committers have signed the CLA.<br/><br/>:white_check_mark: grooverdan<br/>:white_check_mark: brad0<br/>:x: sysprg<br/>:x: montywi<br/>:x: dr-m<br/>:x: abarkov<br/>:x: knielsen<br/>:x: vuvova<br/>:x: denis-protivensky<br/>:x: mariadb-DebarunBanerjee<br/>:x: Thirunarayanan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MariaDB/server?pullRequest=3694) it.</sub>

2025-04-13 19:51 UTC, vuvova requested changes
questions re. test cases.
and please, rebase it on top of 10.11

2025-04-13 19:51 UTC, vuvova commented on sql/item_jsonfunc.cc
> +                               0, "comparison", (int)((const char *) je.s.c_str - js->ptr()));
is there a test case for that?

2025-04-13 19:51 UTC, vuvova commented on sql/item_jsonfunc.cc
> +                            0, "equality comparison", 0);
is there a test case for that?

2025-04-13 19:51 UTC, vuvova commented on strings/json_lib.c
> +      return -1;
it looks like there **is** a test case for that, but, please, confirm

2025-04-17 09:03 UTC, grooverdan commented on sql/item_jsonfunc.cc
> +                               0, "comparison", (int)((const char *) je.s.c_str - js->ptr()));
No. In looking for one, it has to:
* be comparison like `SELECT JSON_EXTRACT('{"n": "aaaa\\ud834\\udd1e"}', '$.n') = 'value' as invalid_utf8mb4;`
* pass the current connection character set. this is validated in the `j->val_str` at beginning of the function, easy - set to binary
* pass the escape syntax which is valid utf16 which the two code points above are.
* by the time it passes to my_wc_mb_utf8mb4 to validate the utf8mb4, the byte seqeunce has been converted its high/low surrages have been converted down to the valid utf8mb4:
```
Thread 4 "mariadbd" hit Breakpoint 9, json_handle_esc (s=0x7f043a1ea8a8) at /home/dan/repos/mariadb-server-rebase/strings/json_lib.c:322
322	    uchar code[4]= {0,0,0,0};
(gdb) c
Continuing.

Thread 4 "mariadbd" hit Breakpoint 8, my_wc_mb_utf8mb4 (cs=0x6aa4db8 <my_charset_utf8mb4_bin>, wc=119070, r=0x7f0424029f1c "𝄞", e=0x7f0424029f28 "")
    at /home/dan/repos/mariadb-server-rebase/strings/ctype-utf8.c:3056
3056	  if (r >= e)
(gdb) p/x wc
$38 = 0x1d11e
```

So my chatgpt ai says that there isn't a high/low surrogate when resolve that forms a character that isn't valid utf8.  So at the moment, code unreachable.

2025-04-17 09:26 UTC, grooverdan commented on strings/json_lib.c
> +      return -1;
nope, there doesn't appear to be, at least in 10.11. based on above, I'm not sure it reachable.

2025-04-17 22:01 UTC, grooverdan commented on sql/item_jsonfunc.cc
> +                               0, "comparison", (int)((const char *) je.s.c_str - js->ptr()));
To clarify further the test case I added would have failed, but since utf8mb4 was set as the character set it didn't fail.

The number of times a validation occurs could be optimised and if it is, this codepath might be hit. It could be replaced with a debug assert, but its a test and function call so there's not much gain to optimise this further.

2025-04-18 22:55 UTC, merged