MDEV-34924 : gtid_slave_pos table neven been deleted on non replica n…
MariaDB/server pull request #3718
Opened 2024-12-19 07:47 UTC by janlindstrom

…odes (wsrep_gtid_mode = 1)

- [x] *The Jira issue number for this PR is: MDEV-34924*

## Description

Problem was caused by MDEV-31413 commit 277968aa where mysql.gtid_slave_pos table was replicated by Galera. However, as not all nodes in Galera cluster are replica nodes, rows were not deleted from table.

In this fix this is corrected so that mysql.gtid_slave_pos table is not replicated by Galera. Instead when Galera node receives GTID event and wsrep_gtid_mode=1, this event is stored to mysql.gtid_slave_pos table

Added test case galera_2primary_replica for 2 async primaries replicating to galera cluster.

Added test case galera_circular_replication where async primary replicates to galera cluster and
one of the galera cluster nodes is masterto async replica.

Modified test case galera_restart_replica to monitor gtid positions and rows in mysql.gtid_pos_table

## Release Notes
TODO: What should the release notes say about this change?
Include any changed system variables, status variables or behaviour. Optionally list any https://mariadb.com/kb/ pages that need changing.

## How can this PR be tested?

TODO: modify the automated test suite to verify that the PR causes MariaDB to behave as intended.
Consult the documentation on ["Writing good test cases"](https://mariadb.org/get-involved/getting-started-for-developers/writing-good-test-cases-mariadb-server).

If the changes are not amenable to automated testing, please explain why not and carefully describe how to test manually.

## Basing the PR against the correct MariaDB version
- [ ] *This is a new feature or a refactoring, and the PR is based against the `main` branch.*
- [ x] *This is a bug fix, and the PR is based against the earliest maintained branch in which the bug can be reproduced.*

## PR quality check
- [x ] I checked the [CODING_STANDARDS.md](https://github.com/MariaDB/server/blob/-/CODING_STANDARDS.md) file and my PR conforms to this where appropriate.
- [ x] For any trivial modifications to the PR, I am ok with the reviewer making the changes themselves.

2025-01-09 11:58 UTC, temeo requested changes

2025-01-09 11:58 UTC, temeo commented on sql/wsrep_schema.cc
> +  Wsrep_schema_impl::wsrep_off  wsrep_off(thd);
Turning wsrep off here causes the first statement to run with wsrep OFF. If `mysql.gtid_slave_pos` table is InnoDB table, this causes the transaction to be started with wsrep OFF. As the wsrep status is synced only at the beginning of the transaction in InnoDB, this causes the rest of the transaction to run with wsrep OFF too.

2025-01-12 15:51 UTC, bnestere reviewed
Hi @janlindstrom !

In general I think the approach works. See my comments for some specific suggestions/questions.

Also, where your git commit message does a good job explaining _what_ the patch does, it doesn't cover _why_/_how_ this approach works (which I think it should).

2025-01-12 15:51 UTC, bnestere commented on sql/wsrep_schema.cc
> +    (void)trans_commit(thd);
I'm not really familiar with the Galera code - when in the transaction life-cycle is `store_gtid_event()`/`wsrep_apply_events()` called? It looks to me like this is before any of the transaction events have actually been applied. If so, and then we update & commit `mysql.gtid_slave_pos` here before actually applying the DDL, then if something happens while the DDL is running and we restart, `gtid_slave_pos` would be ahead of the actual database state.

2025-01-12 15:51 UTC, bnestere commented on sql/wsrep_schema.h
> +     Store GTID-event to mysql.gtid_slave_pos table.
I think it would be good to extend this comment to explain why it is needed.

2025-01-12 15:51 UTC, bnestere commented on mysql-test/suite/galera/t/galera_restart_replica.test
> +#  - Verify that we can shutdown and restart Galera replica (node #2)
In our previous email exchange, you noted an extended use case for this, where (adapting it to this test) `node_2` would go down, and there would be an SST from `node1`->`node_2` , and then `node_2` would need to restart at the correct slave position. I think it would be good to extend this (or one of your other) test cases to handle that.

2025-01-12 15:51 UTC, bnestere commented on mysql-test/suite/galera/t/galera_2primary_replica.cnf
> +slave-parallel-threads=2
I think it would be good to set `gtid-cleanup-batch-size` differently on the mariadb nodes, to add a layer of verification on the reason of a lesser `gtid_slave_pos` table size. I' dsuggest, on one node, made it _really_ big, so the cleanup never happens; and on another node, keep it small. Then your validations would be more strict (rather than just `< 1000`).

On the node with a really big `gtid-cleanup-batch-size`, you could validate that `SELECT COUNT(*) FROM mysql.gtid_slave_pos == <domain_3_seqno> + <domain_4_seqno>` (note the `gtid-cleanup-batch-size` value should be much more than `<domain_3_seqno> + <domain_4_seqno>` (`2006`), as previously run tests can impact the cleanup time).

And on the node with a small `gtid-cleanup-batch-size`, you should be able to assert `SELECT COUNT(*) FROM mysql.gtid_slave_pos < @@gtid-cleanup-batch-size`

2025-01-13 10:47 UTC, janlindstrom commented on mysql-test/suite/galera/t/galera_restart_replica.test
> +#  - Verify that we can shutdown and restart Galera replica (node #2)
See line 59, we intentionally force SST (here it does not matter which Galera node is donor) and at line 70 node_2 is restarted and because it has skip-slave-restart=0 slave thread is started.

2025-01-13 10:53 UTC, janlindstrom commented on sql/wsrep_schema.cc
> +    (void)trans_commit(thd);
In case of DDL, it is problematic. If GTID event is executed before DDL, it will be committed anyway as DDL does implicit commit before start. IF GTID event is executed after DDL it is also not atomic with DDL.

2025-01-14 01:01 UTC, sysprg commented
@janlindstrom Thanks, the fix has been merged with the head revision: https://github.com/MariaDB/server/commit/133e26fd7dc454c5b154495ab876c76bbcfd1715
@bnestere I accept this patch as the current working version after your review which generally finds no problems here in light of Jan's explanations - since without fixes from this commit we will not close the current issues for customers and will not be able to move on to solving the next critical issue: https://jira.mariadb.org/browse/MDEV-20065 since the Codership team needs this fix as a prerequisite for a future PR on MDEV-20065. I propose that all future improvements, if we deem them necessary, be made as separate MDEVs.

2025-01-14 01:01 UTC, closed without merging